### ISSUE TITLE
Determine client-side stack

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#1]
Primarily for @ahankinson :
- Where do we stand on React? Am I good to go, or should we make time to go over how it works, potential issues, etc. at some point?
- I'd like to test out using [Flow](http://flowtype.org/), a JS type checker. It works in part by using type annotations embedding in the source files. These are a strict superset of JavaScript (the annotations just get stripped out while building) and have first-class support in Babel, which is now the default transpiler in JSPM. I'm mentioning it only because strictly speaking it goes beyond ES6 syntax. (If we're going with React, then using [JSX](https://facebook.github.io/jsx/), which is a similarly well-supported syntax extension, will be pretty much necessary.)

Also, TODO for me:
- [x] Integrate some kind of live reloading with jspm (maybe by proxying jspm-server?)
- [x] Work out front-end testing setup. This will probably be Karma + Jasmine + [this reporter](https://www.npmjs.com/package/karma-spec-reporter) with whatever extras I need for jspm, [React](https://www.npmjs.com/package/react-shallow-testutils), etc. Code coverage would also be nice.
- [x] Linting using ESLint, since JSHint doesn't seem to provide enough flexibility for the parser and working with JSCS is _super_ unpleasant.
- [x] CSS probably using a stripped-down build of Bootstrap (maybe just the reset stylesheet, typography, and buttons), using the official Sass port

**Edit:** Flux things
- [x] I had been thinking of implementing what would basically be a buggy reimplementation of [this](https://github.com/faassen/reselect), so that will be useful

**Comment by ahankinson** [comment]
1. React is a go. Try to get a handle on [Flux](https://facebook.github.io/react/docs/flux-overview.html). I'm wondering if we can avoid duplicating "models" on the client side and just fetch things directly from the server as needed.
2. Flow looks good. Probably your first task is to start putting together a gulpfile that builds a pipeline of checkers and processors. ++ on the linters.
3. Live reloading example: https://github.com/DDMAL/diva.js/blob/master/gulpfile.js#L107. Not necessarily the only way, but it's worked so far.
4. Bootstrap sounds OK too.

**Comment by wabain** [comment]
For Flux, I've been looking at [Redux](https://github.com/rackt/redux), which is supposed to make the flow of logic clearer than standard Flux implementations ([e.g.](https://gist.github.com/gaearon/d77ca812015c0356654f)). If I don't go with that I'll probably use [Flummox](https://github.com/acdlite/flummox). I'll definitely be using some kind of centralized data manager rather than standalone models, though.
