### ISSUE TITLE
Standardize status codes in the status view.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#10]
Right now there's the possibility or returning any status codes straight from celery (RETRY, STARTED, REVOKED). It would be more consistent and a better API if all these mapped into one of three codes - PROCESSING, SUCCESS, ERROR.

**Comment by ahankinson** [comment]
They should also be defined as constants with integer values, rather than as strings, e.g., 

`settings.py`:
PROCESSING = 1
SUCCESS = 0
ERROR = -1

`somecode.py`:
status = settings.PROCESSING

**Comment by agpar** [comment]
It's better to serve an int as the status over http?

**Comment by ahankinson** [comment]
It's certainly smaller... 

You could expose the statuses in root endpoint of the API, so that JS clients can auto-configure themselves and know that 1 = processing. 

See the 'configuration' section of the Rodan root response: http://rodan-dev.simssa.ca/?format=json

**Comment by agpar** [comment]
Fixed in 0f0bcaad06dc745d9d02d515c32228a07b37161d
