### ISSUE TITLE
Import IMSLP collection

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#100]
The IMSLP has a collection at the internet archive:

https://archive.org/details/imslp

We should figure out how to get all the identifiers from this collection and import them all.

**Comment by ahankinson** [comment]
Also, 💯 !

**Comment by agpar** [comment]
So, about 9000 imslp manifests from internet archive are coming in now.

**Comment by ahankinson** [comment]
Only 9000?

**Comment by ahankinson** [comment]
:-P

**Comment by ahankinson** [comment]
I see you imported Stanford as well.

BTW, nice manifests now on IA. 😄

**Comment by agpar** [comment]
Yeah, it says 20 000 on the page, but it doesn't want to show me any more pages after page 133 (with 75 results per page), so I'm not sure what that's about.

**Comment by agpar** [comment]
Ok - managed to get all 26 000 identifiers from their search. Will start the big job soon!

**Comment by ahankinson** [comment]
whoa.

**Comment by agpar** [comment]
Looks like we got them all.
