### ISSUE TITLE
Import Gallica

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#101]
```
http://gallica.bnf.fr/services/engine/search/sru?operation=searchRetrieve&version=1.2&startRecord=0&maximumRecords=50&page=1&query=%28gallica%20all%20%22Manuscrits%20musique%22%29%20and%20dc.type%20all%20%22manuscrit%22%20sortby%20dc.date%2Fsort.ascending
```

This should retrieve all the musical manuscripts. Doing this call with content negotiation will get you the JSON representation:

```
$> curl -XGET -H "Accept: application/json" ...
```

From there, the Gallica response can be parsed and the Manifest IDs generated. This should result in about 4,775 results.

Also available is all scores:

```
http://gallica.bnf.fr/services/engine/search/sru?operation=searchRetrieve&version=1.2&page=1&query=(dc.type%20all%20%22partition%22)
```

Same process; this should result in just over 40,000 manifests.

**Comment by ahankinson** [comment]
FYI, I think the results are paginated, so you'll probably have to loop through the pages to get them. And the JSON they return is... uhm... well, I trust you'll figure it out. :)

**Comment by agpar** [comment]
Yo that's a 4 MB json response.

**Comment by ahankinson** [comment]
Good luck, soldier.

**Comment by agpar** [comment]
Something like 10% of the results are links to other libraries which host the files... I'm going to log these, but ignore them for now, since they have different IIIF set ups that I don't want to figure out right now.

**Comment by agpar** [comment]
Also, not sure if this search is clear enough. There's a lot of handwritten letters _about_ music.

**Comment by ahankinson** [comment]
It comes from here: http://gallica.bnf.fr/html/und/partitions/partitions

**Comment by agpar** [comment]
Gallica manuscripts and scores have been imported. Had to remove and update the list of manuscripts, since it turned out all but 800 of them were letters. Luckily, they were easy to remove. The list of manifests we attempted to import and the results of those imports are saved on the server.

I have the script I used to parse through their search results for info. I could edit it to be a little more modular and include it in the repo somewhere.

**Comment by ahankinson** [comment]
Yes please. Could you also contact Malcolm and get his script for Internet Archive?

**Comment by agpar** [comment]
Sure thing. I've sent him an email.

**Comment by agpar** [comment]
I wrote a [re usable search scraping class](https://github.com/DDMAL/musiclibs/blob/dev/misirlou/helpers/harvesters/search_scraper/search_scraper.py) that we can hopefully apply to many libraries. It's a super-class that has all the logic for doing rate limiting and multi threaded fetching. All that a child class needs to define is how to work through pagination of results, and how to turn a response into a list of manifests. Hopefully this will be helpful for quickly adding new libraries... we can pretty easily scrape any sites search that will give us a json response.

**Comment by agpar** [comment]
I think we have this finished.
