### ISSUE TITLE
Server improvements

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#103]
The musiclibs.net server could do with a couple tweaks: 
- Enable gzip. Right now it's sending 660KB JS uncompressed. Gzip should be enabled for all static files (JS, CSS) and even content coming from Django.
- Update nginx. Nginx 1.4.6 was released over two years ago. Update nginx to 1.9+

**Comment by agpar** [comment]
Ah - gzipping was turned on, it was not yet configured on the proxy server (which, by default, unzips things before sending them back- doh).

I just installed nginx via the ubuntu 14 apt program. You think it's worth adding a non-statndard nginx repo or compiling from source to get this upgrade?

**Comment by ahankinson** [comment]
You can get packages directly from nginx.org. 

http://nginx.org/en/linux_packages.html

Just look at the "For Debian/Ubuntu" section. We probably want 'stable' and not 'mainline'

**Comment by agpar** [comment]
Does it matter to you if the backend servers are running new nginx? Or just the web facing router.

**Comment by ahankinson** [comment]
We should probably standardize as much as possible...

**Comment by agpar** [comment]
Ok I'll add the stable nginx ppa to everything then.

**Comment by agpar** [comment]
Actually, I've re-thought it, and I don't think that makes much sense. It should make sense to have the most updated stable nginx at the web facing end, if only for performance improvements. But I don't think we get any benefit from going around the standard ubuntu nginx on the individual projects. It's actually _less_ standard to be subverting the version standards that ubuntu defaults to. 

Further, I envisioned the project leaders as being responsible for the nginx configs on their projects - I don't think I should be going around and messing with the cantus and rodan nginx configurations. 

There should be no problem with the version of nginx running on the backend machines... Half the internet is running on ubuntu 14 servers, and they are probably all running the default nginx version. Most of the updates between now and then appear to be small fixes and HTTP 2 support.

**Comment by ahankinson** [comment]
I want to run http/2 :)

**Comment by agpar** [comment]
Ok - I'll talk to ryan and jerome about it tomorrow (for the cantus and rodan support).

**Comment by agpar** [comment]
We spoke about this briefly and decided that HTTP2 support was only important for musiclibs. The router and musiclibs server have been updated to nginx version 1.10 and are pulling from the `stable` nginx repo rather than the default ubuntu.
