### ISSUE TITLE
Upload broken?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#105]
I can't seem to upload manifests on production... It just sits there and spins.

https://iiif.archivelab.org/iiif/imslp-musices-odhecaton-petrucci-ottaviano/manifest.json

Looking at Celery, it looks like the queue is full of checking tasks, so that any upload will not get executed immediately. This should be fixed so that uploads and checking are in different celery queues.

**Comment by agpar** [comment]
Ohhh yeah - that makes sense. We've never imported such a big volume as we did earlier this week. Hadn't thought about the test jobs clogging the queue.

**Comment by agpar** [comment]
The server now has two celery workers, one each on the `test` and `import` tasks. Thus, testing should no longer block importing.
