### ISSUE TITLE
Look into IA manifest creation.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#106]
IA might be able to provide us with more robust manifests. Have a look here.
https://github.com/ArchiveLabs/iiif.archivelab.org/tree/master/iiify

**Comment by agpar** [comment]
I've put in 2 pull requests that should fix 2 issues.

https://github.com/ArchiveLabs/iiif.archivelab.org/pull/13
https://github.com/ArchiveLabs/iiif.archivelab.org/pull/14

**Comment by ahankinson** [comment]
This is so fantastic. Thank you.
