### ISSUE TITLE
Add musiclibs to IIIF Awesome

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#107]
https://github.com/IIIF/awesome-iiif

Probably could be added to the 'discovery' section.

**Comment by agpar** [comment]
Before I put in the pull request:

`[Musiclibs](musiclibs.net) provides cross-library search of thousands of musical scores and manuscripts` ?

**Comment by agpar** [comment]
[It is done.](https://github.com/IIIF/awesome-iiif/pull/38)

**Comment by ahankinson** [comment]
:+1:
