### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#109]
I just clicked on a random document on the front page, and retrieved this:

https://musiclibs.net/manifests/58ca5099-5392-48ee-a274-bc6aa88f22a5

However, if I do a search for "Ghebart" I don't retrieve this source (it says no sources found). If I do a search for "Ghébart" however, I do retrieve the source.

So I think we need to make sure we index by mapping extended ASCII / UTF to ASCII. On DIAMM I think I solved this with the `ICUFoldingFilterFactory` Solr filter:

https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.ICUFoldingFilterFactory

Field definition:

https://github.com/diamm/diamm/blob/master/solr/conf/schema.xml#L76

You will have to do a bit of custom finagling, since the ICU extensions are not installed by default but are shipped with Solr. On a Mac, they are available in `lib` and `lucene-lib` in `/usr/local/Cellar/solr/6.0.0/libexec/contrib/analysis-extras/`. You need to copy `lib/icu4j-56.1.jar` and `lucene-lib/lucene-analyzers-icu-6.0.0.jar` to your CLASSPATH (I do `/usr/local/Cellar/solr/6.0.0/server/solr-webapp/webapp/WEB-INF/lib`).

**Comment by agpar** [comment]
Looks like we should have stuck with python2 ;)

**Comment by ahankinson** [comment]
Why?

**Comment by agpar** [comment]
Solving unicode issues by putting head in sand.

**Comment by ahankinson** [comment]
Why is there no "head in sand" emoji? #frustrated

**Comment by agpar** [comment]
One annoying issue is that accents can either matter all of the time or none of the time. Do you think we should just always fold accented characters down to ascii?

**Comment by agpar** [comment]
This has been addressed in 56845cefd2f0cf7f7dbad570ebeb0f3e7a79db47 and is pending movement onto master.

Searching for `ghebart` will find the manifests, but the highlight currently shows it as being part of the `spellcheck_txt` field, which is a little silly.

**Comment by ahankinson** [comment]
as long as you fold both query and indexers with the same filter, you should be fine. I noticed that your filter chain for query and for indexing is different -- I wonder if this will cause problems? It basically means that what people type, and what is available to be searched, can be slightly different.

**Comment by agpar** [comment]
Thats for the suggester - the only difference is stopwords are filtered out at index time, but not at query time.

So, when you type `the` you will get `themes` suggested. `the` is ignored at index time, but `the` is not ignored at query time (so you can get suggestions for words whose prefix is a stopword, without having a stopword ever suggested for you).

**Comment by agpar** [comment]
Except that I'm wrong and I put it on the `all_lang` field type instead of the `spellcheck` field type, haha. Will fix tomorrow.
