### ISSUE TITLE
Celery returns SUCCESS on non-JSON data

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#12]
When the url of a non-JSON resource is POSTed to /manifests/, Celery (and therefore the /status/ endpoint) indicate a SUCCESS status, as well as giving an error message:

``` json
{
    "error": "Data is not valid JSON",
    "status": 1
}
```

Steps to reproduce:
- POST to /manifests/ with remote_url=`http://example.org/`
- Wait until the returned status is no longer pending

**Comment by agpar** [comment]
You need to restart celery I think. The tasks in celery's brain don't get updated when the files are changed... That error message is coming from the online validator, which is not being used in the current version.

When I try to import that url

```

{
    "exc_message": "Expecting value: line 1 column 1 (char 0)",
    "trace": "Traceback (most recent call last):\n  File \"/home/lexpar/Documents/DDMAL/misirlou/env/lib/python3.4/site-packages/celery/app/trace.py\", line 240, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/home/lexpar/Documents/DDMAL/misirlou/env/lib/python3.4/site-packages/celery/app/trace.py\", line 438, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/home/lexpar/Documents/DDMAL/misirlou/misirlou/tasks.py\", line 22, in create_manifest\n    if not wip_man.create():\n  File \"/home/lexpar/Documents/DDMAL/misirlou/misirlou/tasks.py\", line 52, in create\n    self.__retrieve_json()\n  File \"/home/lexpar/Documents/DDMAL/misirlou/misirlou/tasks.py\", line 101, in __retrieve_json\n    self.json = json.loads(manifest_data)\n  File \"/usr/lib/python3.4/json/__init__.py\", line 318, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.4/json/decoder.py\", line 343, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.4/json/decoder.py\", line 361, in raw_decode\n    raise ValueError(errmsg(\"Expecting value\", s, err.value)) from None\nValueError: Expecting value: line 1 column 1 (char 0)\n",
    "exc_type": "ValueError",
    "status": -1
}
```

A trace is being printed because I'm doing a json.dumps without even checking that the content is json. My validate function is commented out because the online validator was giving me incorrect output, and I haven't set up a replacement yet.

**Comment by wabain** [comment]
Makes sense. We should document this stuff at some point.

**Comment by wabain** [comment]
Would this be useful? http://celery.readthedocs.org/en/latest/userguide/workers.html#autoreloading

**Comment by agpar** [comment]
Looks like it!
