### ISSUE TITLE
Don't expose too much info in trace

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#13]
The internet is a big, bad place. I would be careful about exposing too much information about the workings of Python by returning the raw stack trace, since this could (potentially) be used to find vulnerabilities in the system.

Instead you should make sure the error is logged, and then return an informational message to the user about why the manifest couldn't be processed.

**Comment by agpar** [comment]
Okay. Would something like this be better?

```
{
    "error": "server error",
    "error_type": "UnicodeDecodeError",
    "status": -1
}
```

Or is even exposing the exception name a bad idea?
