### ISSUE TITLE
Format search results to mimic IIIF search API.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#14]
It would be good to format the search results to be similar to the IIIF search API. Even though this API only defines behaviour for searching within a single manifest, it might be advantageous to follow it closely. Especially if at one point we decide we'de like to return results at a granularity smaller than manifests. Continued from #5 

http://search.iiif.io/api/search/0.9/

**Comment by ahankinson** [comment]
It might be a good idea to add a IIIF Response Writer to Solr. 

https://cwiki.apache.org/confluence/display/solr/Response+Writers

**Comment by agpar** [comment]
The more I think about this, the more I think it's not very useful for what we're doing. Most of this API is for dissecting the importance/placement of results within the manifest... Imitating it really gives me nothing besides aesthetics.

**Comment by wabain** [comment]
Maybe serving results as a [Presentation API collection](http://iiif.io/api/presentation/2.0/#collections) would make sense?

**Comment by agpar** [comment]
Yes, we could do that (the search response API is very similar). But, it seems like this would be a purely aesthetic decision and is possibly dishonest.

For instance, a Collection MUST have an `@id` attribute with the collection's URI. If we're just serving up search results here, then what can we put in this field? The query that created it? Obviously it won't be a static description of the collection...

Plus, naming the IIIF api in the `@context` seems problematic, since we're just co-opting the format we like but not actually respecting the intentions of the formatting guide.

How about something like this?

```
{
    '@id': 'https://example.com/search/?q=exam&page=1',
    'q': 'exam',
    'next': 'https://example.com/search/?q=exam&page=2',
    'last': 'https://example.com/search/?q=exam&page=5',
    'startIndex': 0,
    'results':[
          {
               '@id': remote_url,
               'label': 'blah',
               'description': 'blah',
               'thumbnail': some_url;
               'attribution': 'blah';
               'hits': [
                    { 
                         'field': 'metadata',
                         'prefix': 'I have an',
                         'exact': 'exam',
                         'suffix': ' today.'
                     }
                ]
            }
      ...
    ]
}
```

**Comment by ahankinson** [comment]
An ID can be a non-resolvable URI I think -- so `http://example.com/search/[SOME UUID HERE]/` would be a valid ID.

**Comment by agpar** [comment]
I'm not sure I understand your example - what is this ID referring to? On our current set-up, your example would 404.

**Comment by ahankinson** [comment]
It's a URI -- it doesn't have to be de-referenced, it just has to be unique.

**Comment by agpar** [comment]
So - we wouldn't be putting anything at that URI... It's just there to be there?

**Comment by agpar** [comment]
Because you're not saying we should save search results...

**Comment by ahankinson** [comment]
Exactly. As far as I understand, an `@id` just has to be unique, it doesn't actually have to reference anything, right?

**Comment by agpar** [comment]
Well in the IIIF API its supposed to reference a copy of the object it's nested in.

"`@id` and the value must be the HTTP URI from which the Collection’s description can be retrieved."

**Comment by ahankinson** [comment]
OK, then I'm wrong.

**Comment by agpar** [comment]
So, right, If we explicitly use the Search or Collection API, I feel like we're writing a check we can't cash... they're just not designed for what we're doing, and we're going to end up breaking (maybe not syntactic, but conceptual) promises of the API. The example I posted above is pretty close to them in terms of organization and aesthetics, so unless you guys have suggestions or criticisms that's how I'd like to go.

**Comment by wabain** [comment]
I don't really mind one way or the other, but I don't think there's actually anything that keeps the collection API from being fit for our purpose. (It's worth noting that search results are actually one of their use cases, although they only mention it briefly.)

The `@id` URI is just the HTTP address from which we serve the result. There isn't (as far as I can see) any guarantee that the collection will stay the same if it's dereferenced multiple times. The conceptual promise is that the results which are served are the ones which satisfy the description of the resource. In this case, that description would be "whatever manifests best match the query."

Are there any other ways we would be violating the intentions of the API?

**Comment by agpar** [comment]
Collections have no concept of pagination (unless you include pages 2-n as sub-collections).
Empty collections are discouraged (we can't control this).
And again, I think the fact that the URI will reference a description that could change multiple times a day is not within the spirit of the object (I note, with some confusion, that you are correct that they included 'search results' in the use case).

But I think you're convincing me a little that using the Collections might not be totally flagrant.

**Comment by wabain** [comment]
Pagination is a good point. The sub-collection relationship doesn't really seem good enough for that purpose since we don't want a list of all paginated subcollections.

If we were to introduce a different way of doing it (which we could; there's probably a decent standard for it out there and JSON-LD allows multiple contexts) I think we would still be violating the implicit ontology that using a collection suggests. While I don't think changes to the results list violate the spirit of the API as long as there's a logical reason for it (e.g., the resource which match have changed), having multiple co-equal collections which represent concepts that aren't intrinsically useful like "results n to m" and then having those collections linked using out-of-band data _does_ seem like a violation.

Anyway, what you're proposing seems like a pretty good API to me.

**Comment by wabain** [comment]
Looks like pagination will be in version 2.1 of the Presentation API (not that it changes anything for this issue):
- http://iiif.io/api/presentation/2.1/#paging-properties
- https://github.com/IIIF/iiif.io/issues/598
