### ISSUE TITLE
Restrict ability to update/delete manifests

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#15]
Just noting this so that we get to it eventually: Currently, the `ManifestDetail` view is implemented as a `RetrieveUpdateDestroyAPIView`. We probably at least want to restrict the ability to update or delete manifests to admins.

**Comment by agpar** [comment]
Fixed in 240d039e04a9a55b2d7eb2be62e71e16724e2c4d

Detail view is only retrieve now... Hard to think I've why we're really need posting/deleting to the detail view.
