### ISSUE TITLE
DOM errors with Diva

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#16]
I get intermittent errors when trying to instantiate Diva after the first time it's run. Usually these involve trying to take `textContent` of `null`.

**Comment by ahankinson** [comment]
@affogarty had similar problems a while back, I think. It usually had to do with a phantom DOM node that was no longer there. Are you calling the Diva destructor when you destroy the first instantiation?

**Comment by wabain** [comment]
Yes, but IIRC Cantus Ultimus does some other things to clean up as well.
I'll see if those resolve it here but hopefully I can track down the cause.

**Comment by wabain** [comment]
Looks like this isn't really a Diva problem. It was a bug in my React integration code.
