### ISSUE TITLE
Determine content of search results

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#17]
Regardless of the format determined as a result of #14, we should work out what information is included in the search results. Where available I'd like to display:
- the label
- the manifest thumbnail
- the attribution
- maybe the English-language description since the label isn't always very informative, although I don't know how well this would fit with highlights on the page

I'll also need the uuid (preferably under that name for consistency, unless we're going the JSON-LD route and it needs to be `@id` or something).

@lexpar I think most of this is pretty similar to what you landed in ed0ca3813226928937c77a3fb5674ab71e64c61e? Adding highlights also sounds good to me.

**Comment by agpar** [comment]
attribution and thumbnails can't be guaranteed - but I can include them if they are there on a search response. Do you want simply a link to the thumbnail (its `@id`), or the entire service block?

description is also not guaranteed - language preferences certainly not guaranteed. On some libraries they include multiple translations, but lots of libraries simply include a `description`, which is typically in the native language of whichever library it is (not easy to figure out what language it is dynamically... although, I think I've seen some solr language detection stuff).

uuids are being stored as 'id' in solr, but I suppose its early enough to change that.

I'm not intending this post to be a solution, just letting you know the lay of the land.

**Comment by ahankinson** [comment]
Thumbnails are pretty easy -- if they're not specified, just request the first image (or a random image) at thumbnail size.

**Comment by agpar** [comment]
NB: I've re-factored 'uuid' to 'id' as this issue highlighted the fact that this name was out of place. I know this wasn't exactly what you were getting at Will, but I believe this is more sensible than continuing to use 'uuid' to refer to what solr and django default to naming the id.

247e77daf94d398c16277c1010a887c1308a2e01

**Comment by wabain** [comment]
I think this is pretty much covered, or it falls under #21.
