### ISSUE TITLE
Search spell suggestions to return?

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#18]
Hey Will, I know you're out this week but I'd like to get your opinion on this eventually.

I've implemented spell checking in solr, and it can give us a tonne of information, I think maybe too much. Here's the spell checking output on a search for 'pari est dimnlz"

```
"spellcheck": {
    "suggestions": [
      "pari",
      {
        "numFound": 4,
        "startOffset": 0,
        "endOffset": 4,
        "suggestion": [
          "paris",
          "part",
          "parti",
          "partie"
        ]
      },
      "est",
      {
        "numFound": 1,
        "startOffset": 5,
        "endOffset": 8,
        "suggestion": [
          "et"
        ]
      },
      "dimnlz",
      {
        "numFound": 1,
        "startOffset": 9,
        "endOffset": 15,
        "suggestion": [
          "dimna"
        ]
      }
    ],
    "collations": [
      "collation",
      {
        "collationQuery": "paris et dimna",
        "hits": 2,
        "misspellingsAndCorrections": [
          "pari",
          "paris",
          "est",
          "et",
          "dimnlz",
          "dimna"
        ]
      }
    ]
  }
```

As you can see above, we have suggestions for each individual word of the phrase (pari = paris, parti, etc) and also collations, which are entire suggested phrases which will produce results, based on the last query (there can be many of these).

I don't have this wired up to do type-ahead suggestions (that can be done too!), but I would like to know how much of this information you think is relevant. 

I actually think the single highest rated collation is probably enough, and then typeahead can be a distinct thing.

**Comment by wabain** [comment]
I agree. Having the one collation with the list of corrections should be
good. Having typeahead would be great!

**Comment by agpar** [comment]
Okay, so the json coming from the back end will look like this:

```
...
q: "paris est Dimnlz",
collations: {
    collationQuery: "paris et dimna",
    misspellingsAndCorrections: [
        "paris",
        "paris",
        "est",
        "et",
        "dimnlz",
        "dimna"
    ],
    hits: 2
},
...
```

 'collations' is a dict with a single suggestion in it, or is null.

If you like, mispellingAndCorrections list could be massaged a little more on the backend, but you'll have to tell me what you'd like.

**Comment by agpar** [comment]
As for type ahead, the way I did that on ElvisDB was to have a  `/suggestions` endpoint which queried a specific solr request handler and returned an almost-no-formatting-at-all list of suggestions for a single word. As the user was typing I would take the current value of the input, split it on spaces, and send whatever the last thing in that split was as a query to `/suggestions`, then dump whatever it gave me back into a list the user could see. 

We could simplify this a bit by just having a `?suggest=true` query parameter on  the`/search` view which indicates you're looking for suggestions and not full query results. Does that sound all right to you?

**Comment by wabain** [comment]
I think it would make more sense to have a separate endpoint for it, but I'm not too picky.

Now, if I _am_ going to be picky about something can we call `collations` something like `spellingSuggestions` instead? I don't think the meaning of collations is very obvious when it's not part of a `spellcheck` object. (And then maybe `original` or `query` instead of `collationQuery`.)

**Comment by wabain** [comment]
I went ahead and changed the key from collations to spellcheck.

**Comment by agpar** [comment]
Good call. As we talked about here, I've added an endpoint for typeahead suggestions at /suggest.
