### ISSUE TITLE
Import URL verification.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#2]
Should URL verification (checking that the given URL returns JSON, checking that the JSON has the basic requirements of a IIIF manifest) be done on the front-end or the back-end?

If it's done on the back-end, then there's the issues of:
- Either taking a long time to respond when a link is invalid (waiting for a timeout)
- Or sending back an 'Accepted' response immediately, doing the verification on another thread, and having another URL to actually check the results of the import (this sounds overly complicated to me).

Which makes me think that checking that at least the manifest URL returns JSON and is has the basic requirements of a IIIF manifest on the front end could be better.
- User can't actually submit an import until JS determines that the URL in the input field returns something.
- Posting to back-end will actually return the sort of response you would expect - either an error message or a 'Created' status - instead of a redirect url.
- Avoiding awkward state where a request is sent in, and there is a long wait which appears to come from the backend, only to result in a timeout because the manifest URL was invalid or unreachable for some reason.

What do people think?

**Comment by wabain** [comment]
Doing it on the frontend is (1) theoretically insecure (easy to just post
to the endpoint) and (2) means that import can't be done via a public REST
API.

There's also a question of how much code we would have to push to the
frontend to do validation, but that seems less severe.

Is there no way to get the request to stay pending while we handle
validation of the main thread? The timeout case doesn't worry me too much.

**Comment by agpar** [comment]
No, it's not impossible, I'm just not very happy with any of the ways I can think of doing it.
1. Return ACCEPTED and start processing - no feedback to user.
2.  Add 'indexed' field to manifests, on POST create a Manifest in the DB, return URL to this manifest (/manifests/[id]). This URL will return a response saying either "still indexing", "error while indexing [description]" or will actually return the link to the manifest if it was successfully indexed.
3.  Do the above, but with a new 'TempManifest' model, so we don't end up with big gaps in the pk-list where some guy tried to import the same faulty manifest 12 times.

I would lean towards 3. Can you think of a better way?

**Comment by ahankinson** [comment]
If it's just validation then it shouldn't take too long. Try validating a large manifest with Python and see how long it takes. If it's less than half a second I wouldn't worry about it.

**Comment by ahankinson** [comment]
Both 1 and 2 are good. You might think about using uuids as the pk. (See rodan for example)

**Comment by wabain** [comment]
What about 3 but with an ImportStatus model instead of TempManifest? I'd
prefer an API where if I  GET a manifest and receive a 200, then the
resource is valid and good to go.

**Comment by ahankinson** [comment]
If you're using celery you can query it to get the status of any job. 

See: https://github.com/music-encoding/customeization/blob/master/customeization.py#L143

An extra model just for holding status seems like more code to keep in sync. I would go for a field on the manifest model that indicates its indexing status.

**Comment by wabain** [comment]
Using Celery sounds fine. What I really want is a distinct endpoint or status code.

**Comment by ahankinson** [comment]
Did you see this?

http://restcookbook.com/Resources/asynchroneous-operations/

Return a 202, with a status URL (/status/[celery-id]). No model is needed there.

**Comment by wabain** [comment]
That's what I had in mind

**Comment by agpar** [comment]
If I'm just returning a link to status/[celery PID], then I don't need the 'indexed' field on manifests, as I'll only create the Manifests if the import goes OK.

**Comment by wabain** [comment]
So I think where we are right now is:
- If you POST to `/manifests/`, you get a `202 Accepted` response with a JSON body. That JSON contains a field like `"status": "http://example.org/status/[id]"`
- Doing a GET on `/status/[id]` returns a JSON object which indicates whether import is ongoing, was successful, or failed.
- Doing a GET on `/manifest/[id]` while import is ongoing, or if there is an error, either:
  1. Is impossible, because a resource only exists if the import completes successfully, or
  2. Results in a `303 See Other` redirecting to the status page
- Doing a GET on `/manifest/[id]` after the import has successfully completed returns a representation of the manifest resource.

**Comment by agpar** [comment]
:+1: Agreed

**Comment by ahankinson** [comment]
Man, I love it when esoteric HTTP status codes get used properly. `303 See Other` is brilliant. This sort of thing gets me up in the morning.

**Comment by ahankinson** [comment]
Point 4: The corollary of point 3b: If you request a status for an object that _has_ been created, it 303s you to the manifest.

**Comment by ahankinson** [comment]
That last one might be tricky, since it would require keeping the Celery IDs around and redirecting them. Perhaps it's understood that these expire periodically.

**Comment by agpar** [comment]
I'm keeping results of process around using djcelery (creates and manages a database table for CELERY_RESULT_BACKEND - we could flush this every so often, but its probably small). So 3b/4 is handled by getting the celery process results and returning a 303 if it was a SUCCESS.

We spoke about and agreed to return 404 on a GET to `manifests/[id]` if the manifest is still processing or failed to be created.

**Comment by wabain** [comment]
I seem to have uploaded the same manifest for St. Gallen 391 from e-codices three times while developing. There should probably be some kind of deduplification going on on the backend. I don't know what that should look like in terms of the API, though. I guess we redirect in response to the initial POST?

**Comment by agpar** [comment]
This is worth having a separate issue to discuss.

**Comment by agpar** [comment]
I would say this issue is closed, given that the project is now firmly in the 'validate asynchronously and offer a status page" camp.
