### ISSUE TITLE
Show metadata with Diva view

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#20]
Should show the metadata for the document at the same time as viewing it. Right now only the title is visible.

**Comment by wabain** [comment]
Any thoughts on security here? The only definite thing I think I should be doing is ensuring that links in the metadata aren't to `javascript:` URIs (I'll whitelist `http`, `https`, and `mailto`). Mirador doesn't [seem to be](https://github.com/IIIF/mirador/blob/190a6e9d4d63eaee034e9a50278b8c274e346b23/js/src/widgets/metadataView.js#L121) doing any special handling around this. I haven't checked the Universal Viewer.

I haven't decided how I'm dealing with HTML values, either. Right now I'm just presenting strings like

> `<span>From: <a href="http://digital.bodleian.ox.ac.uk/inquire/p//eeb272cc-bb48-44b0-9ee3-2cee0338a691">Digital.Bodleian</a></span>`

to the user, but I guess I should either be stripping it out or using the prescribed whitelist of safe HTML elements. Rendering this stuff with React is probably safer than just doing string manipulation, but there are still probably potential dangers.

**Comment by wabain** [comment]
Oh, it looks like browsers actually have support for doing [HTML parsing in a separate document](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser). That makes this easier - I can parse HTML content and then traverse the output DOM and take whitelisted HTML elements, or just their text.
