### ISSUE TITLE
Thumbnails of first page in search results

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#21]
Would be cool to show a sample page in the search results.

**Comment by wabain** [comment]
IIRC this (well, showing the IIIF thumbnail anyway - I assume showing the first page would also be pretty easy) is the plan. It's just a matter of getting the relevant fields in Solr. Maybe @lexpar can confirm.

**Comment by agpar** [comment]
I'm haven't written an algorithm to either find a thumbnail or grab the first page and index it as a thumbnail yet. Like Will said, should be simple once I write that.

**Comment by agpar** [comment]
Would you like me to process the thumbnail urls before indexing them @wabain? If I get a IIIF image service, I can just generate the url for that image at 150px wide and index that. That way, all there is to do on the frontend is plop in the indexed url.

**Comment by wabain** [comment]
Not totally sure, but I think it would be best to return an image service if one is provided. I already want code to handle those for the institution logos on the manifest detail page, so doing it for thumbnails shouldn't require much extra work, and I might want to vary the requested size based on the size of the user's viewport.

**Comment by agpar** [comment]
Okay then. I'm thinking of making 2 thumbnail fields, `IIIF_thumbnail` and `thumbnail` - so you can easily figure out if you have a thumbnail you can manipulate or not (both are acceptable in the IIIF api).
Sound ok?

**Comment by wabain** [comment]
That kind of detection logic is also something I'll be implementing on the client-side, so just having one `thumbnail` field would make sense to me since, as you say, either a URL or a service block is legal in the Presentation API.

**Comment by agpar** [comment]
So do you want the whole service block? As it is, I'm just pulling the `@id` out of there.

**Comment by wabain** [comment]
Yeah, it should probably be the whole service block, in case it contains other information I need (for instance, the supports property - see DDMAL/diva.js#297).

**Comment by ahankinson** [comment]
PS: You guys are awesome. Thanks for the attention to detail.

**Comment by agpar** [comment]
:+1: 

@wabain with f4c48cf0803e932308c2182bd5f0e2bc04851ece thumbnails should be up and running on pretty much anything you import.
