### ISSUE TITLE
Title can be a list

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#22]
This manifest generates an error:

http://dams.llgc.org.uk/iiif/4574752/manifest.json

Looks like the title code can't handle it when a title is a list.

```
File "/.../misirlou/misirlou/helpers/WIPManifest.py", line 118, in _solr_index
    label = settings.SOLR_MAP.get(m.get('label').lower())
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by agpar** [comment]
This issue was for all metadata labels which were lists. This should be fixed in cba0d33cbb1daf24419e1c8826ebd9a22473ec51 with the addition of _meta_label_normalizer().
