### ISSUE TITLE
Support collections

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#23]
Collections can be a way to bulk import.

See.
http://iiif.io/api/presentation/2.0/example/fixtures/collection.json

See also:
https://graph.global/universes/iiif

**Comment by agpar** [comment]
Are you interested in maintaining this collection structure? i.e.: Should collections be a type of model/relationship/field that our indexes reflect, or do we simply treat it as a bulk import?

**Comment by agpar** [comment]
Also - distinct point for importing collections, or catch and handle when posted into /manifests?

**Comment by wabain** [comment]
I think it should be the same upload point, personally. I wouldn't want users to have to make a distinction, and the client won't have enough information to make the distinction for them.

**Comment by agpar** [comment]
I agree.

**Comment by ahankinson** [comment]
Same upload point, treat as a bulk upload

**Comment by agpar** [comment]
Perfect.

**Comment by agpar** [comment]
That example collection is insanity. Is it especially designed to contain every possible edge case?

I guess it is, given every manifest is called test.

**Comment by wabain** [comment]
One case it doesn't have is subcollections, which seems important here.

**Comment by agpar** [comment]
Well, that example just went down. That makes testing stuff more difficult.

**Comment by ahankinson** [comment]
The Biblissima Collection seems like a nice test set: 

https://graph.global/static/data/universes/iiif/biblissima.json

You can find more of them at the 'graph global' link. You could _try_ importing the Internet Archive and see what happens. ;)

**Comment by agpar** [comment]
That collection fails immediately for not having an `@id` parameter, which is mandatory. I'm getting frustrated. So many libraries seem to only sort of or half implement this stuff. It's not even like including the `@id` attribute is hard: its just the url of the current resource.

**Comment by ahankinson** [comment]
You should send an e-mail to the IIIF mailing list and point this out. No need to suffer in silence.

**Comment by agpar** [comment]
Isn't it the bibilissima people I should be yelling at?

**Comment by ahankinson** [comment]
Not if it's systematic -- just point out some of the problems with the collections that you're working with, and they should fix it. The easiest way to reach these people is through the IIIF mailing list.

**Comment by agpar** [comment]
92ebc32b7872b30cca1e6f9030c75fee63aa75d2 has WIP code for collection importing. I figured out that I could include progress indicators with the status reports from celery, so @wabain you should use those to make a more menacing status bar when a collection is being imported (the progress{current:i, total:j}} member will only show up in a response from /status  if a collection is being imported ).

I've turned off the strict `@id` requirement for now, as it was killing the vibe on these ~1000 manifests I wanted to import.

**Comment by ahankinson** [comment]
Great, thank you! You should still send a note around to the IIIF mailing list asking about this.

**Comment by wabain** [comment]
I haven't had a chance to read the commit but this sounds good! Will progress.total ever increase? I'm wondering about a scenario where pulling in subcollections causes the total number ot rise. I wouldn't want the progress indicator to go backwards. I guess I'll have to work out the logic for that - the progress percentage shouldn't be linear.

Also, what's returned on success? And is success determined at the level of collections or manifests (e.g. can some import successfully while others fail?)

**Comment by agpar** [comment]
No, the total won't grow. The collections import feature runs in two steps. It recurses into the sub collections and compiles a complete list of all the manifests it needs to import, and then works from that list.

As for what it returns on success, either the same thing as a single manifest returns on success (the success code and a list of warning/errors), or I forgot to write that part. The error/warning list will have the url's of manifests as keys. Success is >=1 manifest importing correctly. Those that failed to import will be noted in the error dict.

**Comment by wabain** [comment]
Sounds good! I'll be able to work out any corner cases once I play around with it.

**Comment by agpar** [comment]
I didn't think much about the status yesterday, in reality, they completely broke since they were trying to send you a redirect to a manifest. In any case, 77ba6b1c6a32afb20e93b91d5fc477bdf5900038 now includes really detailed status reports for collection importing. Hopefully this gives you the tools to build a nice interface!

**Comment by agpar** [comment]
I think we need some fronted handling for large collections... Something like a popup or modal when we see that the collection being imported has over 25 or 50 manifests in it. We inform the user that the process will continue even if they leave the page, and we give them the url to look at the results of the import (it should be the same URL you are polling for progress information).

**Comment by fujinaga** [comment]
How long are we talking about? Few seconds, minutes?
Can we not give the user something to look at?

**Comment by wabain** [comment]
I believe right now we throw up a progress bar while the import is ongoing.

@lexpar is the concern here that there's no way to get information on the upload if you leave the page? That's something we can work on. I'll be in tomorrow most of the day if you'll be around.

**Comment by agpar** [comment]
On my laptop, about .5 manifest/second, so half an hour for a collection with a thousand things.

There is a loading bar, as @wabain mentioned, but nothing to let you know you can leave the page and check the results later.

**Comment by ahankinson** [comment]
Is this because of the latency of HTTP requests?

**Comment by agpar** [comment]
The processing speed? That's probably a big part of it. Right now the validation is still happening with the IIIF validator, which actually does all the HTTP requests a second time, and appears to be quite slow. That's one of the big things to be rewritten.

**Comment by agpar** [comment]
Here's an example of the final response you'll get if you import the Yale collection. This is running on the new validator.

I would say support for importing collections is essentially implemented, except for some fronted stuff. I still think we need some type of 'this might take a while' warning, and we might want some nice way to display these results to people.

Also, the UI says the upload failed when it gets the response below, which is odd to me as it still contains a `status: 0` entry.

```
{  
   "type":"collection",
   "status":0,
   "succeeded":55,
   "total":69,
   "error":{  
      "http://manifests.ydc2.yale.edu/manifest/Buddha":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/B1992_8_11":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/OxfordCorpusChristiMS198Multispectral":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "URI is not valid: cf. Boydell & Brewer hardcopy catalogue for dictionary value @ data['related']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/WGSS120":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/Scroll":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/B1981_25_403":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/B1992_8_1":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/BNFLatin3895":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "required key not provided @ data['sequences']['canvases']['images']['resource']['service']['@context']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/YCBAB1981_25_278":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/BodleianMS_Lat_liturg_e_17":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "required key not provided @ data['sequences']['canvases']['images']['resource']['service']['@context']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/B1981_25_404":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/OxfordCorpusChristiMS198":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "URI is not valid: cf. Boydell & Brewer hardcopy catalogue for dictionary value @ data['related']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/BlakeCopyL":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      },
      "http://manifests.ydc2.yale.edu/manifest/BeineckeMS748_5":{  
         "status":-1,
         "errors":[  
            {  
               "validation":[  
                  "expected int for dictionary value @ data['sequences']['canvases']['width']"
               ]
            }
         ]
      }
   },
   "failed":[  
      "http://manifests.ydc2.yale.edu/manifest/B1992_8_1",
      "http://manifests.ydc2.yale.edu/manifest/OxfordCorpusChristiMS198Multispectral",
      "http://manifests.ydc2.yale.edu/manifest/B1981_25_404",
      "http://manifests.ydc2.yale.edu/manifest/BeineckeMS748_5",
      "http://manifests.ydc2.yale.edu/manifest/BodleianMS_Lat_liturg_e_17",
      "http://manifests.ydc2.yale.edu/manifest/Scroll",
      "http://manifests.ydc2.yale.edu/manifest/OxfordCorpusChristiMS198",
      "http://manifests.ydc2.yale.edu/manifest/BlakeCopyL",
      "http://manifests.ydc2.yale.edu/manifest/BNFLatin3895",
      "http://manifests.ydc2.yale.edu/manifest/WGSS120",
      "http://manifests.ydc2.yale.edu/manifest/YCBAB1981_25_278",
      "http://manifests.ydc2.yale.edu/manifest/Buddha",
      "http://manifests.ydc2.yale.edu/manifest/B1992_8_11",
      "http://manifests.ydc2.yale.edu/manifest/B1981_25_403"
   ]
}
```

**Comment by wabain** [comment]
I believe it says it failed because it can't find the link to the uploaded manifest. I'll update the front-end code probably next week.

**Comment by agpar** [comment]
I tried to have all the manifests in a collection be imported concurrently (since CPU usage is not that high for me when I'm importing), and the speed has not increased very much.

My guess that SQLITE is a big bottleneck. Each import requires a range selection, read, and a possible delete. Currently celery is also storing its results on the database as well (so every ping of the loading bar is a read, every started task is a write, every completed task is 2 writes). The SQLITE database-wide write lock is probably hurting the process a whole lot.

If we move celery results to redis, that would probably speed up the process a lot (as it's doing a TON of writes during a collection import). Maybe we should consider if we want to move to a tougher DBS as well.

**Comment by agpar** [comment]
That's just a guess though. It could be that sending results to solr is slow (that could be an async call). It could be that the validator is slow (although, my cpu usage stays low even when processing 20 manifests concurrently).  Certainly the http requests add some unavoidable time. 

I'm open to ideas guys!

**Comment by ahankinson** [comment]
Sqlite is horrible for anything other than development. It should be pretty easy to move to Postgres.

**Comment by wabain** [comment]
Moving to Postgres sounds fine to me. Have you tried using cProfile to see what's going on? (I don't know how that interacts with Celery.)

**Comment by musicus** [comment]
Using sqlite should just be verboten.

**Comment by agpar** [comment]
Switching to psql gets us up to like 2 manifests/second on my laptop. :+1:

**Comment by ahankinson** [comment]
I suspect most of that is the HTTP request overhead.

**Comment by agpar** [comment]
Yes I think so. I just pushed some concurrency stuff for celery now, so it should be able to make 20 concurrent http requests while importing a collection. It seems to have sped things up quite a lot.

**Comment by ahankinson** [comment]
There's currently a discussion on the IIIF mailing list about the impact of concurrent collection harvesting. What collections are you hitting?

**Comment by agpar** [comment]
I've been testing using http://manifests.ydc2.yale.edu/manifest

**Comment by agpar** [comment]
Right now we're not doing any automated harvesting... We just grab all the manifests in a collection, and any manifests in sub collections. It's a downward process that never tries to branch out sideways.

I suppose we should be ramping up to the point where we can more intelligently crawl a library for manifests. Any thoughts?

**Comment by agpar** [comment]
I would say collection importing is supported at this point. When we start doing more web-crawl-y stuff, we can open more issues.
