### ISSUE TITLE
HTML in search results

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#29]
It looks like HTML elements are being indexed in Solr. Not sure what the best way to handle it would be.

![screen shot 2016-01-22 at 12 24 36 pm](https://cloud.githubusercontent.com/assets/7651435/12517893/395b592a-c103-11e5-8277-a22e9b6f9ec7.png)

**Comment by ahankinson** [comment]
https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.html.strip_tags

**Comment by agpar** [comment]
What kind of a monster would put HTML in json?

**Comment by agpar** [comment]
I think handling this at index time is the best option. Saving this here for reference.
https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.HTMLStripCharFilterFactory

**Comment by agpar** [comment]
Never mind - it has to be handled before sending the document to solr.

**Comment by wabain** [comment]
Why? Out of curiosity.

**Comment by agpar** [comment]
The solr HTMLStripCharFilterFactory will strip the HTML from the index, and it can strip HTML from queries, but solr doesn't actually modify the stored field. I don't think it ever actually modifies the stored value - just applies filters to whats indexed.

So even with the HTML filter factory, the query 'that repository' will return the entire 'repository' field, `<a href='...'> [$]that repository[$] I found it in</a>`

**Comment by wabain** [comment]
In that case it definitely sounds like it would be easier to strip HTML beforehand, although FWIW the really pathological case is when the match breaks the HTML, like `<[$]a[$] href="...">`. If it were guaranteed that matches would only be on text rather than within tags, as in your example, I could work with that.

**Comment by agpar** [comment]
The HTMLStripCharFilterFactory would prevent the behaviour you're talking about (as only 'that repository I found it in' would be indexed, to use the above example). But, I still think for the fields that I'm matching on (like repository, attribution, label, etc.) it makes sense to strip HTML before sending it to solr.

**Comment by agpar** [comment]
@wabain mentioned the other day that it would actually be better to strip HTML from the stored documents. I have something working on a local branch, but right now it's just hitting every text value in a manifest and attempting to strip html from it. This seems likely to be bad. 

Is html stripping only necessary on descriptive/metadata fields? That would narrow things down nicely.

**Comment by wabain** [comment]
To clarify, I only meant that HTML should be stripped from search results - it should still be included in the full manifest. So the relevant ones should be (I think) label, description, attribution, hits. The IIIF spec says that HTML is only allowed in description, attribution, metadata. I can't remember if people tend to honour that.

**Comment by agpar** [comment]
So, you want the `label` in your search result to be html stripped, but the `label` in the full manifest which solr stores to not have html stripped?

**Comment by wabain** [comment]
Yes. Although I guess I can do it on the front end easily enough if that's a problem.

**Comment by agpar** [comment]
Thats no problem. I just have to move a few lines around.

**Comment by agpar** [comment]
I've tested the changes on 4e295303b9afd5ed143c2bd9f75028a5b1fb95e6 with the manifest you linked me, and everything seems to be in in order.
