### ISSUE TITLE
Don't validate remote manifest content type

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#3]
Currently we're checking the `Content-Type` of manifests during import and seeing if they're correct (i.e., JSON or JSON-LD). However, some providers don't have it set correctly. For instance, e-codices is sending them as `text/html`, and I suspect that kind of thing is pretty common IRL. Since we're validating the format of the content anyway it should be safe to just disregard the content type.

**Comment by ahankinson** [comment]
Or we can contact them and ask them to change it. That's one of the things I want to do with this project is help our sources provide better IIIF resources.

**Comment by ahankinson** [comment]
@lpugin Do you know who we might contact at e-codices to ask about their web serving infrastructure?

**Comment by wabain** [comment]
There's also a typo in the content of their IIIF manifests we should let them know about (`see_also` instead of `seeAlso`).

**Comment by wabain** [comment]
Worth noting that [currently](https://github.com/DDMAL/misirlou/blob/748faca8ce4275faad612d896999d2252434d6d7/misirlou/helpers/validator.py#L46) our validation makes bad content types a warning rather than an error, so the original purpose of this issue has pretty much been addressed.

**Comment by agpar** [comment]
I'm likely going to be writing a validator based on json schema validation and a stripped down py2/3 script which only detects warnings - so yeah, we can close this.
