### ISSUE TITLE
Front page?

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#30]
Hey Will,

I pulled master and started it up and I don't think I'm seeing anything on the landing page. Can you send me a screenshot of what it's supposed to look like?

**Comment by wabain** [comment]
Did you remember to `npm run build`? Are there any errors in the console?

![screen shot 2016-02-05 at 11 18 04](https://cloud.githubusercontent.com/assets/7651435/12851885/46dcff5c-cbfa-11e5-9aa3-991aab456d4a.png)

**Comment by wabain** [comment]
I assume this works now?

**Comment by agpar** [comment]
Yes!
