### ISSUE TITLE
Save copy of thumbnail locally?

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#31]
It might be good to save a low res copy of the thumbnails for documents in the database. This way, when displaying the table of thumbnails on the front_page, you don't end up waiting 10-15-20 seconds for the library to return the thumbnail.

Is this against the spirit of the project? It would be purely for a smoother user interface.

**Comment by ahankinson** [comment]
I would do it with some sort of caching mechanism rather than in the database.

Are you really seeing long waits for these images? Most services I've seen are pretty quick.

**Comment by wabain** [comment]
Actually, I meant to open an issue about this. The wait isn't to get the thumbnail - right now we're loading all the manifests on the front-end and then getting the thumbnails from there. Really the image URL/Image API service block is what we should be saving locally.

**Comment by ahankinson** [comment]
Ah. How many manifests are you loading on the front end? (You said "All"... do you mean ALL of them??)

**Comment by wabain** [comment]
Yeah, "all" definitely isn't accurate. I think it's the 12 most recent or something like that. And it might be done lazily as they're displayed, but there's still latency as the fetch is performed.

**Comment by agpar** [comment]
Oh I see! Well, the thumbnails should be indexed in solr and returned with any search request. So, using those would likely give us all the speed up necessary.

It looks like I'll have to add an 'indexed' timestamp to the solr records to get the most recently indexed.

**Comment by agpar** [comment]
What I mean to say is that links to thumbnail images or text dumps of the json of an image service are being indexed in solr.

**Comment by agpar** [comment]
We have automatic index timestamps in solr now. If you do an empty search and sort by `index_timestamp` descending, you can get the basic properties of the last imported manifests (including a thumbnail).

**Comment by wabain** [comment]
I think currently I take the most recently created manifests. Would it make sense to just add that to the Solr document? From what I can tell it isn't there now, but I don't have a running server to check at the moment.

**Comment by agpar** [comment]
If I understand what you wrote, that's exactly what I've done.

**Comment by wabain** [comment]
As I understand it, `index_timestamp` is automatically set to the time when the document was updated in Solr, whereas the `created` field on the Django model gives the time the manifest was initially imported, and doesn't change when we reindex it. Does that sound right?

**Comment by agpar** [comment]
Yes that's correct Will. I don't see it as being an important distinction for this use case (deciding which thumbnails to display).

Maybe it could be in the long run though... I can index the created in DB date.

**Comment by agpar** [comment]
A manifest's thumbnail data is now indexed in solr, and returned in any search request. We may investigate caching image data in the future, but that may be overkill.
