### ISSUE TITLE
Storing manifests in Solr

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#32]
@ahankinson, at some point during development we brought up the idea of saving a dump of the entire manifest in solr, as a stored but not indexed field. I can't remember the justification for that now, and I'm itching to remove it. 

Is there something I'm forgetting? I don't see the usefulness. Maybe it was that we were worried about the manifest at a URI changing and us not knowing... But, I think in that case we should just erase what we had an index whatever is stored there now.

**Comment by ahankinson** [comment]
We need the manifest to show the Diva view, and thought this would be quicker than resolving it and would bypass some same origin weirdnesses.

**Comment by agpar** [comment]
Hmmm... It might be quicker to store manifests in PostgreSQL than solr, even then, it probably wouldn't be very quick. I have about 1600 manifests on my laptop now, and an empty query to get full records takes a few seconds to complete on solr. Then again, Will isn't using solr to fetch manifests now, so maybe it's fine to not store them at all.

**Comment by ahankinson** [comment]
That's very very strange. Is it taking this long to complete the query, or to render the result in your browser?

**Comment by wabain** [comment]
Is that for all 1600 manifests?

**Comment by agpar** [comment]
I'm guessing it's actually mostly the rendering time. And Will, that would be for a page with 10 manifests printed out on it.

Should I add an endpoint to get the stored manifest? I already whipped up a solr request handler that turns `id`s into manifests. What would be an appropriate endpoint for this? `/manifest/${id}/?retrieve=true`, or something like that?

**Comment by agpar** [comment]
We will definitely continue to do this. Storing manifests in solr speeds up their retrieval and ensures we can display data about the manifest without mixed-content issues.
