### ISSUE TITLE
Move front-end bundling from JSPM to Webpack

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#33]
Currently, we use JSPM as a package manager and bundler for client-side code. Unfortunately, JSPM forces a very slow development workflow (which the developer indicates isn't going to change anytime soon) as well as various tooling woes. I still haven't gotten it to work with Karma, for instance.

Meanwhile, npm has released new features which make it much easier to use it as the package manager for front-end code (notably, dependency deduplication and reliable versioning for nested dependencies). This makes it more attractive to move to using Webpack as a bundler, which I know I can get working quite easily and will resolve those issues.

**Comment by ahankinson** [comment]
_sigh_ JavaScript tooling sucks. I'm inclined to agree with you. I've played around with webpack and find it adequate, so I say go for it.
