### ISSUE TITLE
Collection importing is *too* concurrent.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#34]
I'm worried that the way things are set up now, the importer is getting a little too close to being a nuisance for libraries... Since a collection import prompts 20 threads to start pulling data and importing, it is making at least 1 (and likely several) bursts of http requests to the same host on the order of 20/second.

I'll have to break the import task into discrete steps in order to avoid this and apply some rate limiting to the getter task.

**Comment by ahankinson** [comment]
Is there any way of dividing them up by host? As in, if you've got a bunch to harvest from `http://example.com` and 'http://foo.com` that you can run those in parallel, but rate limit for each host.

I'm currently drafting an e-mail to the IIIF community to get some feedback on this.

**Comment by agpar** [comment]
That's what I'm hoping to do... The top level import task will look around for running `get_remote_resources` tasks, which will expose the netloc of where it is pulling resources from. If it finds one that is already pulling from a netloc, it will wait to set up its own `get_remote_resources` task. Something like that.

**Comment by ahankinson** [comment]
Is there a queueing system you can use? Then you could pre-sort the hosts into buckets. 

But really I wonder if this is useful... If you're importing a collection, you're presumably also importing manifests all from the same host. So this would really only be useful if you're importing many collections from many libraries simultaneously...

**Comment by agpar** [comment]
That's a good point. We can either:
1. Not care about the netlocs. Every `collection-import` task can make `x` http requests per second to whatever host it is pointed at. 
2. Not care about netlocs. There is a site-wide limit on how many http requests can be made per second.
3. Care about netlocs. Every netloc can have `x` requests made against it per second.

With 1 we risk going over our planned limit of requests/sec on specific hosts, but that is in the unlikely case that multiple collections are being imported form the same library at the same time. With 2, we slow down the whole site to the slowest importing process. With 3, we guard against the unlikely case from 1, and don't slow the whole site down.

I think either 1 or 3 are fine. Since the advantage 3 offers over 1 occurs rarely, I think we could just do 1.

**Comment by agpar** [comment]
I read your message on the IIIF group @ahankinson... I'm going to feel pretty sad about all the work I put into parallelising the importing if everyone starts putting 5-sec web crawl delays on their libraries :sob:

**Comment by ahankinson** [comment]
Five per second. :)

**Comment by agpar** [comment]
Closing, as master contains code to limit requests to 3/sec/collection (which seems to be plenty fast).
