### ISSUE TITLE
Support `members` property in collections

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#35]
Version 2.1 of the Presentation API will introduce a [`members` property](http://iiif.io/api/presentation/2.1/#collection) for listing the elements subcollections and manifests in a collection. This should be checked in the collection import script. I think this is the only change Misirlou will need for 2.1.

**Comment by agpar** [comment]
They are going to depreciate the `manifests` and `collections` keys? How are libraries supposed to keep up with these kinds of changes?

**Comment by ahankinson** [comment]
It's complete madness! Madness, I tell you! :)

Libraries employ stacks of devs to keep up with these things.

**Comment by agpar** [comment]
Just saying... It's a big change to implement on the third major revision of the API. They must be taking inspiration from Python.

**Comment by ahankinson** [comment]
It's not actually that big, and it's only being deprecated in 2.1, not removed. It will be removed in 3.0.

**Comment by wabain** [comment]
The migration path also seems really straightforward. Just add a viewing hint of individuals to each of the collections and then concatenate collections and manifests.

**Comment by agpar** [comment]
I put a question on the IIIF discus group regarding how we should distinguish between different versions of the API, as there currently seems to be no way to do so, and this deficiency makes it much more difficult to modularise the validation/import process. This issue motivated the question.

https://groups.google.com/forum/#!topic/iiif-discuss/wQwUjyll_-4

**Comment by wabain** [comment]
What validations actually depend on 2.0 vs 2.1? My understanding was that the specs use semantic versioning, so an object conforms to the Presentation API version 2 iff it conforms to the latest 2.x spec.

**Comment by agpar** [comment]
This `members` key did not exist in the 2.0 API, but _can_ replace two of the 2.0 keys in a 2.1 manifest. So, while it's not a mandatory incompatibility, it is version dependent feature which would be much easier to check for if we actually knew which version of the API the document was attempting to comply with.

Like I wrote in the linked post, I'm not sure if knowing what version of the API a document is complying with has general applicability, but it does in this case, and I am willing to bet it would be useful in general.

**Comment by agpar** [comment]
Should be handled here 026c0cc03e16e4c1fa220c7aecf665d4a3175010.
