### ISSUE TITLE
Sources to harvest

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#36]
This spreadsheet contains a lot of potentially interesting and useful manifests.

https://docs.google.com/spreadsheets/d/1apQKFkfBV89BvycaBPN6v-LjeaKaVVMaMUsY6L4KRJo/edit#gid=0

For example:

http://www.digitale-sammlungen.de/mirador/rep/bsb00046459/index.html#93c74c60-9efc-48ee-bc5c-d66ff149ca41

contains some music, and should be indexed.

Just posting this here for future use.

**Comment by agpar** [comment]
Adding an email you forwarded me from the library of Wales.

First email:

> We do have a few publicly available scores including 19th century folk music scores:
> 
> https://viewer.library.wales/4655107
> https://viewer.library.wales/4655492
> https://viewer.library.wales/4654909
> https://viewer.library.wales/4655569
> 
> and some older lute music:
> 
> http://hdl.handle.net/10107/4630018

Second email:

> Regarding the links I’ve sent you below if you wanted to convert them to manifests the manifests URLs are in the following form:
> 
> http://dams.llgc.org.uk/iiif/2.0/4655569/manifest.json
> 
> where 4655569 is the id of the item and is at the end of the viewer urls I sent. We also have ssl versions if that helps:
> 
> https://damsssl.llgc.org.uk/iiif/2.0/4655569/manifest.json
> 
> regarding indexing the metadata are you going to be indexing the metadata section of the manifest or following the see Also link? The manifest above don’t currently have a see Also link but I could investigate adding one. What metadata would you expect I think we could provide MARC/XML, MODS or possibly linked data from our catalogue.

**Comment by ahankinson** [comment]
This is underway. Closing.
