### ISSUE TITLE
Set up musiclibs.net and dev.musiclibs.net

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#37]
Misirlou needs to be deployed on a live site by the end of May so that the process of importing many manifests can begin. This issue will keep track this goal, as there are multiple steps necessary.
- [x] Set up compute canada server for site. 2 cores, 16gb ram, 3TB index volume.
- [x] Figure out https configuration with LetsEncrypt.
- [x] Host dev site using nginx and gunicorn with ssl encryption.
- [ ] Stabilize master branch for short term stable deployment.
- [x] Host main site.

**Comment by ahankinson** [comment]
If you can send me the IP addresses you'll be using I can set up the DNS for musiclibs

**Comment by agpar** [comment]
The site is up. I would say that master is stable enough that we can call this done. Still heavy development, but we're basically ready to go.
