### ISSUE TITLE
Indexing OMR data.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#38]
Currently we have nothing in place to index OMR data associated with a manifest. 

I think @ahankinson and I should discuss how this is accomplished and organized in the LiberUsalis and Salzinnes OMR search systems. I need some idea of how these indexes are represented on these systems in order to implement a system where we can easily port over this data. 

Implementing this feature is necessary for importing existing OMR data, and thus needs to be completed before mid-June to be on track for the July deadline.

**Comment by agpar** [comment]
@ahankinson I'm thinking of essentially copying the [schema of the liber](https://github.com/DDMAL/liberusualis/blob/master/solr/src/main/resources/schema.xml) into a separate core in solr, with the addition of a `document_id` indexed field for distinguishing between the OMR results of different documents. 

It seems much simpler to keep the schema for manifest metadata separate from the schema for OMR data. Are you happy with how the liber indexes OMR data? The liber code doesn't have an abundant amount of commenting, so I would still like to talk with you about this. I suppose it makes sense to keep this format, given [all the tools](https://github.com/DDMAL/liberusualis/tree/master/ingest) we've got for shoving stuff into it.

Does this seem like a realistic path forward? It looks like there's a lot of tools that already exist here to make this process simple, I'm just not aware of what exists and where it is.

**Comment by ahankinson** [comment]
Yes, I would be happy to run you through it, and searching on separate Solr cores sounds like a good plan.

**Comment by agpar** [comment]
The cross core search has been implemented and is working for the salzinnes manifest. All that remains it to import the other manifests needed for the july deadline.
