### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#40]
Misirlou -> Musiclibs

Maybe we need an actual logo?

**Comment by musicus** [comment]
Yes.

**Comment by ahankinson** [comment]
Great! A volunteer. :)

**Comment by wabain** [comment]
Related, we need a favicon.

**Comment by ahankinson** [comment]
As part of this: I would like to rename the repo. Any objections?

**Comment by wabain** [comment]
Sounds good to me. I assume issues get migrated.

**Comment by ahankinson** [comment]
Reassigning to @wabain for the front-end work.
- `<title>` tag still says Misirlou
- Front-page still says misirlou

**Comment by ahankinson** [comment]
![m](https://cloud.githubusercontent.com/assets/163183/15296151/f5023942-1b61-11e6-850d-f5c50269022e.png)

**Comment by ahankinson** [comment]
Thoughts?

**Comment by musicus** [comment]
No _L_?

**Comment by ahankinson** [comment]
🎄  😄

**Comment by agpar** [comment]
What on earth does tree-smile mean?

I think that looks pretty sharp! I like red as a highlight color too (even if I made a joke about Halloween earlier).

**Comment by wabain** [comment]
Shouldn't have closed this (via comment on my commit). There's still the logo and other things.
