### ISSUE TITLE
API changes to integrate into frontend.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#42]
On `dev` branch, you should be aware of the following changes to the API which break current functionality (for the long-term better, I hope).
1. The `/manifests/[pk]` endpoint will now retrieve the json of the requested manifest from Solr and return it. This breaks the Diva viewer; I believe you are expecting a single `remote_url` key which you go after. Now the manifest will be in the place of that key (currently its all top level, but I could put it under a key like `manifest` if that seems more sensible). Note: I pushed this to master.
2. The `/manifests/recent/` endpoint now retrieves data from solr as well. It does a search with a wildcard query, sorted by `created_timestamp` descending. The format of the response is identical to the search results returned from the main search endpoint. The benefit of this is it should be faster (sorting using solr index rather than the non-indexed time stamp in DB), and the thumbnail resource will be returned in the response. You should not have to actually retrieve the manifests on the front page in order to find their thumbnail any more.

Hopefully these changes should be easy to integrate into the frontend. Should be a minimal number of changes, since you were essentially getting all this data through multiple steps before, and can get it in one step now.

**Comment by wabain** [comment]
Are we making `dev` our working branch now that we're working on deployment?

**Comment by agpar** [comment]
We should do that in the very near future. The goal is to have a reasonably stable master branch by the end of the month. I merged master into dev today, so once this issue is closed, we can start working primarily on dev.

**Comment by agpar** [comment]
@wabain I have updated this issue with some more information.

**Comment by agpar** [comment]
https://www.youtube.com/watch?v=3GwjfUFyY6M
