### ISSUE TITLE
User accounts.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#43]
We spoke briefly the other day about adding user authentication to the site. I can't think of any reasonable way to expose `/manifests/import` to the public without it being used poorly. Therefore, the main feature of the user accounts will be to control who has the right to import new manifests onto the site.

It may make sense to offer more control over the site content to the users (deleting, re-indexing, seeing a list of _their_ recently imported manifests, etc.), but I don't think we should consider these cases yet.

**Comment by agpar** [comment]
Django auth is already included in the project. I put up some endpoints at `/api/login` and `/api/logout` that can be posted to in the way you would expect to support logging in and out (8f61007777354c4382a264373119ebdb55e5812f). I chose these urls so `/login` and `/logout` can be fancy pages that just send ajax requests to these endpoints. I think this makes sense, but I'm extremely tired.

Should we just give accounts to people who we want uploading things? If so, do we need to support registration? For the time being, I think a spartan login page will do for the <10 users who will be allowed to login and upload.

**Comment by ahankinson** [comment]
Yes. Make accounts for me and you. Eventually we might want to get others in the lab to help upload stuff.

**Comment by wabain** [comment]
I think the API endpoints can just be `/login` and `/logout` too. Content negotiation FTW.

**Comment by wabain** [comment]
Is this just waiting on client-side support, or are there other blockers?

**Comment by agpar** [comment]
As far as I can tell, waiting on client side.

It's not an urgent issue. In the short term, giving admit accounts to a few people around the lab and instructing them to use the admin interface to log in/out is a workable solution.

**Comment by agpar** [comment]
We can handle logging in and out via the admin interface, and as of 3a542408ecd9f015c10262541ed51634f3a6be14 the frontend will properly send in the tokens for an upload. This is basically ready to go.
