### ISSUE TITLE
Only show uploads button for logged-in users

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#45]
Since we're moving uploads behind a login, we should only show it for logged-in users. It can also be in the footer or somewhere.

If that's gone then I don't think we need the menu bar at the top anymore.

**Comment by wabain** [comment]
A few weeks ago I experimented with a navbar which integrated the page title, like on Cantus Ultimus. I don't know if it's the direction I'd go if I were doing it for real and @jeromepl has already changed some of the relevant code, but I'm pushing my WIP to the branch wip-navbar-change-concept. 

I think that a change like that, plus hiding the menu bar on the landing page where the Musiclibs title is already there, would help with the issue of an empty menu bar taking up too much space.

![screen shot 2016-06-06 at 3 07 09 pm](https://cloud.githubusercontent.com/assets/7651435/15834241/7300e838-2bf8-11e6-8762-3d9513c5f91f.png)

**Comment by ahankinson** [comment]
I like it!

**Comment by jeromepl** [comment]
Following a discussion me and @ahankinson had, it would be really nice to have a a single page application where the search bar along with the search results would move to the left when a search result is clicked. The current "Manifest" page could then slide in from the right and take approximately 60-70% of the page. The search bar could be above everything, like how Google does it.

**Comment by agpar** [comment]
There is no more upload button. We can access the upload page via the url, but can only upload if logged in.
