### ISSUE TITLE
Add live stats on front page

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#47]
Something like "Search XXX sources from YYY libraries" under the search bar.

**Comment by agpar** [comment]
What do you mean by `sources` here? Manifests? Manifests makes sense if this line is in reference to the yet-to-be-implemented ocr indexing and search.

**Comment by ahankinson** [comment]
Not many people would know 'manifests.' Maybe we could just say 'searching YYY libraries' or something.

**Comment by agpar** [comment]
There's a `/stats/` endpoint on dev now to get the numbers needed for this.

**Comment by agpar** [comment]
I've put some stats under the search bar on `dev`.

**Comment by agpar** [comment]
This is done on dev.
