### ISSUE TITLE
Remove 'recently uploaded' section from search results page.

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#48]
The recently uploaded section should only really appear on the front page.

**Comment by wabain** [comment]
So I'm sure I understand this right, is this a change from #25 where you said to have "the results list 'push' the manifest lists down, and then 'slide' up when the search input is cleared"?

**Comment by ahankinson** [comment]
Yeah, I guess I didn't quite understand what I was saying...

**Comment by ahankinson** [comment]
does that screw anything up?

**Comment by wabain** [comment]
No, it's probably as simple as a adding an `if` somewhere.

**Comment by ahankinson** [comment]
`if q`?

**Comment by agpar** [comment]
`if (q !== undefined && q !== null)` if you don't understand js and want to be safe (like me).

**Comment by wabain** [comment]
I think you'd also need `q !== ''`.

**Comment by wabain** [comment]
Should I keep "Recently uploaded" for searches with no results?
