### ISSUE TITLE
Investigate IIIF Search API

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#5]
http://search.iiif.io/api/search/0.9/

**Comment by agpar** [comment]
Just finished reading through this - the focus is entirely on providing search capabilities within a single resource, i.e. allowing one to send a query to `e-codices.com/search/[manifest id]/?q=` and receiving matching canvases and annotations within the single manifest in the URI.

This once again raises the question of how granular we want our search results to be. If we are simply aiming to point users at a manifest that matches their query in some way, then we can't rely strictly on these guidelines as they do not consider the case of returning an entire manifest as a result. We could definitely model our results so they closely match this API though.

If we do want to return individual canvases then we should respect this API on those kinds of results. But if we are considering this, then I think we need to separate out the search feature into two parts - one that searches for manifests and one that searches within manifests. It would be very difficult to rank the relevancy of results when comparing a single canvas to a manifest of (potentially) hundreds of canvases, and we'd be mixing our 'in manifest' results which follow this API with 'out of manifest' results which have no API.
