### ISSUE TITLE
Feedback on remote server failure.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#50]
Right now there is no feedback when a failure is due to being unable to fetch resources from a remote server.

For instance, at this exact moment, https://dev.musiclibs.net/manifests/a324861f-05e7-41cd-9bc6-46a96817f3d3/ displays an empty diva window.

This is possibly because all the images in this manifest are returning a small json error message:

```
{
message: "Djatoka returned HTTP status 401",
parameter: "identifier",
status: 404
}
```

I think we should have some mechanism to warn user's when we get unexpected/unworkable responses from a remote server.

**Comment by wabain** [comment]
Is this a Diva issue?

**Comment by agpar** [comment]
It could be! I think it's up to you whether you want to treat this as a more generalizable issue.

**Comment by agpar** [comment]
Is Diva supposed to be doing anything when it can't fetch a resource?

**Comment by wabain** [comment]
It could do. Were you thinking that this is applicable to other things in Musiclibs?

**Comment by agpar** [comment]
No, I think you're right that it's a diva issue. If you diva viewer could put up some warning when it couldn't retrieve resources, that would be great.
