### ISSUE TITLE
Link to original record

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#53]
If there is a 'seeAlso' link, it should be used to link back to the manuscript's record on the original website. (Can we make an exception for e-codices, which uses 'see_also')

**Comment by wabain** [comment]
Must have missed this somehow.

**Comment by wabain** [comment]
I actually had this implemented already (except for the see_also special case) but I put it at the bottom of the metadata view under the heading "Additional data". The spec describes the linked resource as "a machine readable document that semantically describes the resource with the seeAlso property, such as an XML or RDF description."

Should I give the field more prominence on the basis that the link is actually a user-facing resource?

**Comment by ahankinson** [comment]
Yeah, since the point of the site is to lead people to the libraries where the sources are held.

**Comment by wabain** [comment]
But should that be done via seeAlso? I can't think where offhand, but I'm pretty sure there are sites using seeAlso to link to a Turtle file or something.

**Comment by wabain** [comment]
So after our discussion yesterday I guess I'll give extra prominence to the `related` property.

**Comment by wabain** [comment]
Also `rendering`.

**Comment by ahankinson** [comment]
@lexpar was this fixed in your commit? Can this be closed?

**Comment by agpar** [comment]
I think that's one of Will's commits I merged in. On [this e-codicies manifest](https://dev.musiclibs.net/manifests/862fa6ae-80ef-41c4-a608-c4df397c7a34/) the `see_also` key is rendered as the Additional Data link, so yes, this appears to be fixed.
