### ISSUE TITLE
Musiclibs celery task is FATAL

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#56]
On reboot supervisor doesn't bring up the dev_celeryd task. The error message is `celery.platforms.LockFailed: [Errno 2] No such file or directory: '/run/celery/dev_musiclibs.pid'`

Creating /run/celery and chmod 777 on /run/celery seems to fix it, but this probably won't persist across reboots. Another solution should be found.

**Comment by agpar** [comment]
Celery pid files are stored in /srv/webapps/musiclibs/config now. Tested with a reboot and issue is cleared up.
