### ISSUE TITLE
Search bar that can divide into two parts.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#59]
The search bar on the front page should be able to be divided into two search bars, one for text search and one for pitch string search. We were imagining that the page could start with the full width text search bar, then a button could be used to shrink it to half width and draw another search bar in the remaining space. The second search bar would be used for pitch searches.

This is not a very easy idea to express in text, so when you have a minute @jeromepl, talk to me or @ahankinson for a better idea of what I'm trying to describe here.

**Comment by ahankinson** [comment]
I think this basically describes it. A 'search music' link to the top right of the text input would open a second search box to the right where a user can input pitch names. 

Example search:  (form: "text search box | music search box")

```
salzinnes | edcde
```

**Comment by jeromepl** [comment]
Implemented in merge c77edb38936a1aff0123a15f149cffeb9cd8adb2
