### ISSUE TITLE
Single-page view for searching and results

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#61]
I thought this had made it here, but I guess not. This is a conversation I had with @jeromepl a few days ago.

**EDIT:** It was a comment on #45 

We should move to a 'single page' feel for the application. The motivation for this is to make it act more like a search engine. We should 'slide in' a view of the book from the right when a search result is clicked, instead of completely changing the view to a full-screen of the book.

Users clicking on other search results in the results list (to the left of the book view) will see the view on the right change.

Related to #59: The search input box(es) would move to the top and be always present (see screenshot). 

![image](https://cloud.githubusercontent.com/assets/163183/15930892/2cb230e4-2e23-11e6-8831-e545bb7a03e5.png)

Related to #60: A search result with music input could show the results highlighted on the page images. The navigation interface between these search results is TBD, but I like the idea of showing the original snippet of images with the IIIF url, like Cantus Ultimus does.

**Comment by agpar** [comment]
In the list of results you want images from the IIIF documents of the regions that matched the pitch string?

**Comment by ahankinson** [comment]
I think this is TBD. I like the idea of showing the IIIF document regions as the search results since it shows, directly, where we think the pitch results are. But how we integrate and place them on the page, and whether that is feasible, is an open question.

**Comment by agpar** [comment]
It is definitely feasible to get those results in a search. What I am implementing now is a two step search: a first step that finds all document metadata for the documents which contain the requested pitch sequence (done via a join between the metadata and omr core). The second step is to find up to 4 regions (in paged order) from each of the documents which contain that pitch sequence.

The end result will be a response exactly like a normal metadata search, except each doc will have an extra `omr_hits` result with a list of the pre-computed ngram docs from the ocr core. The front end will be able to take those docs and make a request to the IIIF image server for the regions.

**Comment by ahankinson** [comment]
So. cool. I can't wait to see this. 🎉

**Comment by jeromepl** [comment]
Implemented in merge c77edb38936a1aff0123a15f149cffeb9cd8adb2
