### ISSUE TITLE
Import manifests in preparation for presentations

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#62]
For our presentations, I would like to have a couple hundred IIIF manifests imported and searchable, including Salzinnes and Liber, available on musiclibs.net (production).

I can ask someone else to help find and import IIIF urls, but would like some advice on the best course of action for this. Is it possible to do a bulk upload from a file? A plain text file with one manifest URL per line? I know we can use collection import, but some places don't support collections for just music sources yet.

If we start importing a lot of URLs on musiclibs.net now, will that impede any future abilities to update the site?

**Comment by agpar** [comment]
I implemented bulk uploading from files very quickly a little while ago as a management command, and it eventually made its way [onto dev](https://github.com/DDMAL/musiclibs/blob/dev/misirlou/management/commands/bulk_import.py). I say quickly because line 29 looks pretty silly to me right now. In any case, a few tweaks should bring it up to snuff.

I don't think uploading manifests now would change any future abilities for updates. In the worst case, we do some migrations and re-index in solr.

**Comment by ahankinson** [comment]
Ok, I'll get on this.

**Comment by agpar** [comment]
Should I bring master up to dev before you start on this?

**Comment by agpar** [comment]
Will import as much as possible to main site today.

**Comment by agpar** [comment]
I have yet to import the vatican manifesets, as they seem to be buggy. I am also waiting to import a large collection of stanford manifests until after the presentation. Currently we have about 1600 documents on musiclibs.net.

**Comment by ahankinson** [comment]
what's wrong with the vatican ones?

**Comment by agpar** [comment]
They can be imported, but some problem with their formatting is preventing diva from displaying them. I haven't figured out what it is. Here is one: https://dev.musiclibs.net/manifests/b3d058cc-e4b9-4aa5-bec3-14031a0d6c2e/

**Comment by agpar** [comment]
I believe it's some problem with their image server, since I can't get any of the images referenced by a manifest manually.

**Comment by agpar** [comment]
It was a problem with the custom validator overrides for the vatican! Fixed it in 17149eefa555f3851aee651e2ebd3fa11d942400 and importing their files onto production a we speak.

**Comment by agpar** [comment]
We still have the problem with ad-blockers though... I wonder what we should do about that. Perhaps proxying images through our own endpoint would actually be useful in the general case.

**Comment by ahankinson** [comment]
Complain to the Vatican. I'll go see Benedict next week. :)

**Comment by musicus** [comment]
You are going to see Pope Francis & Emeritus Pope Benedict? Cool.

**Comment by ahankinson** [comment]
Give me a break man, I'm protestant. I can't keep all these popes straight. :)

**Comment by agpar** [comment]
Can we call this done? New requests to import libraries can be put in individual issues.

**Comment by ahankinson** [comment]
Done. 🌟
