### ISSUE TITLE
Add 'about' section to a footer at the bottom of the screen

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#66]
The footer should have:
- 3 small logos: DDMAL, SIMSSA, SSHRC
- A link to the source code on github (could be with the octocat logo)
- A link to the SIMSSA twitter (could be with the twitter logo)
- A link to the SIMSSA site (https:/simssa.ca)
- A link to an 'about' page

**Comment by jeromepl** [comment]
Where can I find logos for DDMAL, SIMSSA and SSHRC?

Also, here are links to the github and twitter logo pages, which contain rules on how to use them:
- [https://github.com/logos](https://github.com/logos)
- [https://about.twitter.com/company/brand-assets](https://about.twitter.com/company/brand-assets)

**Comment by belljustin** [comment]
http://ddmal.music.mcgill.ca/logos

**Comment by jeromepl** [comment]
http://www.sshrc-crsh.gc.ca/about-au_sujet/sshrc-logo-crsh/index-eng.aspx

**Comment by jeromepl** [comment]
Implemented in merge c77edb38936a1aff0123a15f149cffeb9cd8adb2
