### ISSUE TITLE
Indicate content types for manifests

### ISSUE THREAD

**Issue by wabain** [DDMAL/misirlou#7]
Currently, we redirect from the /status/ endpoints to the manifest upon successful import. However, doing this means that there's no great way of telling whether the response received is a status or the manifest itself (without knowledge of the URL structure, which isn't something we should hardcode).

If we're moving to serving cached manifests then this shouldn't be a problem; JSON-LD contexts are easy to detect. Otherwise we should work something else out.

**Comment by agpar** [comment]
The redirect happens automatically in chrome, but if you curl (or use ajax - I assume) to a status page, you will recieve the status and the location of the resourse in the header and body.

```
(env)misirlou|master⚡ ⇒ curl http://localhost:8000/status/8c438719-73e9-4bca-ab17-d34a62615c6f/
{"status":"SUCCESS","location":"http://localhost:8000/manifests/8c438719-73e9-4bca-ab17-d34a62615c6f/"}%
```

**Comment by agpar** [comment]
Sorry - that's in response to what you seemed to be bringing up in the first paragraph, but now that I re-read your title and the second paragraph, I'm not sure I understand your question!

**Comment by wabain** [comment]
Right, I can unpack this a bit. Ajax requests _do_ automatically redirect. Usually you can see the ultimate URL (with some caveats, because Internet, but it should be workable). You can't see all the redirects, and in particular you can't see the status of the redirects.

This means that all we have to work with are the ultimate URL and the headers and content of the ultimate response. I don't want to detect whether we got the manifest by looking at the form of the URL, because that would be really fragile. So I need some reliable way to distinguish between the content type of a "status" response and the content type of a "manifest" response.

**Comment by ahankinson** [comment]
Won't a status response be a 3XX, while a manifest response will be a 2XX? Or am I missing something?

**Comment by wabain** [comment]
The browser will redirect automatically; all we can see is the final 2XX status.

**Comment by wabain** [comment]
b30c4775b1cbb3b77e97825dbf4721b4866924ce makes this moot.
