### ISSUE TITLE
Let's Encrypt auto-renew?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#70]
Is the auto-renewal for let's encrypt certificates turned on?

**Comment by agpar** [comment]
There should be a cron job that runs every week to try and renew the certs.

**Comment by agpar** [comment]
/srv/webapps/musiclibs/logs/ssl_renew shows that the cert renewal was attempted on Monday (correct cron time) and exited when no cert needed renewal.

**Comment by agpar** [comment]
https://community.letsencrypt.org/t/email-address-disclosures-june-11-2016/17025

I got one of these emails. Inspires confidence!
