### ISSUE TITLE
Vatican source gives errors

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#71]
https://dev.musiclibs.net/manifests/6d63bbb6-61ae-4bec-9fff-eea999a01a74

I'm seeing "ERR_BLOCKED_BY_CLIENT" for the images in Chrome. Safari seems to load it OK.

**Comment by agpar** [comment]
Could it be caused by your ad-blocking plugin? I disabled mine and now it seems to work. I wonder why this stopped working overnight.

**Comment by ahankinson** [comment]
Bleh. It's because this manifest generates an ID with '-AD2_' in the URL, which AdBlock Plus automatically blocks.

**Comment by agpar** [comment]
#justVaticanThings

**Comment by ahankinson** [comment]
```
    ^
   /+\
¯\_(ツ)_/¯
```

**Comment by agpar** [comment]
It might make sense to make this a diva issue. If an ERR_BLOCKED_BY_CLIENT shows up when requesting an image, we could pop-up in a warning about client side plugins possibly blocking things.

Then again, this case is pretty far on the edge.

**Comment by ahankinson** [comment]
I'll close this. I think it's been addressed, as far as it can be.
