### ISSUE TITLE
Change 'related material' to 'view on library website'

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#73]
The 'Related material' link on manuscript records should be changed to say 'View on library website.' This makes it clear that the link will take you back to the library's record.

**Comment by agpar** [comment]
It doesn't always, though. This link is just whatever is in the `related` key on the manifest... Which can be pretty much anything. For instance, the `related` key on the Liber manifest links to the [the page explaining what we've done with the liber](http://ddmal.music.mcgill.ca/research/omr/Search_the_Liber_Usualis). The API says this link can be any external resource related to the document.

**Comment by ahankinson** [comment]
I would like it to be pretty clear that we aren't just downloading and re-hosting content -- that all of the data we have comes from the libraries, and that we provide links back to the libraries' sites.

Just like a search engine, the main purpose of musiclibs is as a discovery system for finding things held in libraries, and then taking them back there for more information.

**Comment by agpar** [comment]
I understand and agree with you. What I'm trying to say is that we don't have any guarantee that the 'related' link will be anything in particular.

**Comment by ahankinson** [comment]
Yeah, I know. But that's a political problem, and the best way of dealing with it is by dangling a carrot: "If you use the 'related' key properly, harvesters will be able to link back to your site!"

If we build it, they will something something.
