### ISSUE TITLE
Fix the rapid resizing of the results list when typing in the search input fields

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/misirlou#76]
The results list panel resizes based on the size of its content at the moment, which means when performing a search il will constantly resize and resize the diva viewer at the same time.

**Comment by jeromepl** [comment]
The reason I used max-width here is because the result list can disappear if there are no search results. I think it is a cool feature to have and could be done easily in javascript.
Reopening for discussion

**Comment by ahankinson** [comment]
I would like to see the following behaviour:
- A user searches
- A list of search results appears with no right-hand pane. The width of this list should be about 1/3 of the width of the full page.
- Clicking on a result animates a pane in with the source view, occupying the blank 2/3 of the page
- Clicking on another result animates the old source out and swaps a new one in.

I think we should at least implement this and see if we like it.

For the first week of July, though, I think it is enough to just have the search results pane not constantly resize.

**Comment by jeromepl** [comment]
The result list is now hidden if there is no search query in 8d671bf9de22bebbf0b5a29bb13ffda09437e051
