### ISSUE TITLE
Many corrupted images on compute images.simssa.ca.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#81]
The salzinne image files copied onto [compute canada are all corrupted](https://images.simssa.ca/iiif/image/cdn-hsmu-m2149l4/cdn-hsmu-m2149l4_002v.jp2/full/full/0/default.jpg). [ch-sgs-390](https://images.simssa.ca/iiif/image/ch-sgs-390/ch-sgs-390_038.jp2/full/full/0/default.jpg) and [ch-sgs-391](https://images.simssa.ca/iiif/image/ch-sgs-391/ch-sgs-391_162.jp2/full/full/0/default.jpg) also appears corrupted. 

[Beromunster](https://images.simssa.ca/iiif/image/beromunster/bm_025.tif/full/full/0/default.jpg) and [nl-uu-406](https://images.simssa.ca/iiif/image/nl-uu-406/nl-uu-406_054v.jp2/full/full/0/default.jpg) appear OK, ruling out my initial suspicion that something was going wrong with the jp2 files.

**Comment by ahankinson** [comment]
I'll try it again today.

**Comment by ahankinson** [comment]
An update: It works, sort of. After trying all the most recent versions of Kakadu (v7.5-7.8), none of them seemed to work. What I did to 'fix' it was to copy over the compiled IIP binary and make sure the linked paths were in place, and it seems to work now.

Not ideal, though. I'll leave this open until I can think of something better.

**Comment by agpar** [comment]
Removing from first of july milestone, since the temporary nature of the fix shouldn't affect this milestone.

**Comment by wabain** [comment]
Full-region Beromunster images also seem distorted ([for instance](https://images.simssa.ca/iiif/image/beromunster/bm_001.tif/full/710,/0/default.jpg)). Presumably that's related?

**Comment by jeromepl** [comment]
Cantus Ultimus currently has all the full sized jp2 images for Salzinnes, ch-sgs-390, ch-sgs-391 and nl-uu-406. Would that help anyone? They are all placed in a separate volume on Compute Canada.

**Comment by agpar** [comment]
I was incorrect in calling the images corrupted. According to @ahankinson, the issue was with some bug in the way the IIP software compiled on the server. Thus, alternate copies of the images will not be helpful.

Should we still consider this an open/high priority bug?

**Comment by jeromepl** [comment]
I just finished installing the IIP server on the new cantus server (after running in many issues) so I might be able to help here. Let me know!

**Comment by agpar** [comment]
I don't see a problem with keeping things the way the are now (externally compiled binary running the show). The images we get on musiclibs look right to me.

**Comment by ahankinson** [comment]
@jeromepl what did you do to fix yours?

Once we get cantus running with IIIF manifests, we should switch to serving the images from images.simssa.ca. It centralizes our image server and makes it so that we can build out if we need to support heavier loads.

**Comment by jeromepl** [comment]
The only thing that worked for me was to compile [version 1.0 of iipsrv](https://sourceforge.net/projects/iipimage/files/IIP%20Server/iipsrv-1.0/iipsrv-1.0.tar.bz2/download) directly on the server. Using any precompiled version or compiling from the master branch of the project did not work.
