### ISSUE TITLE
Clicking suggestion no longer works.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#83]
When I type 'salinnes' into the search bar, I get prompted with a 'did you mean "salzinnes"' link, but clicking the link does not populate the search bar with the new query or bring me to the correct page.

**Comment by ahankinson** [comment]
Is it possible to check whether 0 results were found and then trigger another query with the top suggestion? "Found 0 results for salinnes. Searching instead for salzinnes"

**Comment by agpar** [comment]
Yes.

**Comment by ahankinson** [comment]
Cool.

**Comment by ahankinson** [comment]
Should that be a separate issue?

**Comment by agpar** [comment]
Nah, I can put it together fairly quickly!

**Comment by agpar** [comment]
So if a search returns 0 results but solr produces a collationQuery we will automatically do the new search and return its results. I've added an `applied_correction` key to the search block which is a list with the original query at 0 and the corrected query at 1. This can be handled by the front end to alert the user to this information. @jeromepl @belljustin

**Comment by agpar** [comment]
This would be fixed on dev now.
