### ISSUE TITLE
Note on experimental nature of pitch search

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#87]
When a user clicks the 'pitch search' a note should appear somewhere alerting users to the fact that this is an experimental feature and is not available yet for all sources.

**Comment by belljustin** [comment]
Does this work?

![screen shot 2016-06-22 at 4 40 36 pm](https://cloud.githubusercontent.com/assets/8331769/16282756/193654d0-3898-11e6-8845-e89fa1b0fa43.png)

**Comment by agpar** [comment]
Can we make it a different color (reddish/yellowish)? Maybe put it on top of a `<hr>`? It will be possible to get a spell correction message at the same time, and that would result in a pretty big blob of grayish text.

**Comment by ahankinson** [comment]
Does that only appear when pitch search is active?

Another option is just to make the link say "Pitch Search (experimental)"

**Comment by belljustin** [comment]
Yeah, it would only be visible when pitch search is active. Just mocking it up within chrome now

![screen shot 2016-06-23 at 4 37 22 pm](https://cloud.githubusercontent.com/assets/8331769/16319325/d8e10942-3960-11e6-8910-1a3f85f4d966.png)

![screen shot 2016-06-23 at 4 42 52 pm](https://cloud.githubusercontent.com/assets/8331769/16319515/95c25494-3961-11e6-974f-0d485af2782d.png)

**Comment by ahankinson** [comment]
The first picture looks like it shows up when pitch search isn't active...

**Comment by belljustin** [comment]
Yeah - I haven't implemented it. Just doing it in the browser so we can check out what it looks like

**Comment by ahankinson** [comment]
@belljustin this should to in today, if possible, so we can roll it out on musiclibs.net

**Comment by belljustin** [comment]
Yeah, no problem. Which design should we go with?

A
![screen shot 2016-06-27 at 11 37 32 am](https://cloud.githubusercontent.com/assets/8331769/16385708/d286f644-3c5b-11e6-9fe6-e9bc64a9aa9a.png)
B
![screen shot 2016-06-27 at 11 37 50 am](https://cloud.githubusercontent.com/assets/8331769/16385711/d2959d98-3c5b-11e6-8a2d-cbdd38adc719.png)
C
![screen shot 2016-06-27 at 11 38 48 am](https://cloud.githubusercontent.com/assets/8331769/16385710/d28de314-3c5b-11e6-936e-024a7e685034.png)
D
![screen shot 2016-06-27 at 11 39 03 am](https://cloud.githubusercontent.com/assets/8331769/16385709/d28805d4-3c5b-11e6-94d9-d010756e0c40.png)

**Comment by agpar** [comment]
I like the blue box.
