### ISSUE TITLE
Make search more fluid.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#89]
Right now a SearchRequest event gets fired (twice?) every time a character changes in the main input bar. This results in some pretty laggy and slow response time from the search bar, since it can lead to copying some 20KB worth of json between dicts and and checks the DOM for components that need to be reloaded many times in a second (any component that gets the `search` key as a prop will have to re-render on every keypress!).

It feels pretty gross to be typing (or deleting) chars from the search bar and having it chug and lag. We should limit the amount of processing that happens on each keypress. I've thought of two ways we might do this (feedback from @belljustin and @jeromepl requested!)

We can remove the 'query' and 'pitchQuery' keys from the top-level 'search' key, and decouple the events for updating the value of the inputs and performing and caching search data. This way, the typing will launch events that only update a tiny amount of the store and the event for caching the previous search and doing the next search can be debounced until the typing slows down.

Or, we can require the user to hit 'enter' before actually returning any results. I don't think this would be a cop out, by the way. Google still requires you to hit enter on the main searching interface (seemingly only after your search passes some dis-similarity threshold compared to your previous search, but still).

**Comment by wabain** [comment]
The last time I saw performance issues with the search it turned out to just be overhead caused by the React DevTools. I'd be careful to profile the performance issues before doing any work-intensive refactoring.

**Comment by agpar** [comment]
Good advice! The dev site is much smoother than I thought.

**Comment by agpar** [comment]
This seems to be less of a problem on the production site, and would be an enormous amount of refactoring anyway.
