### ISSUE TITLE
Check for duplicate remote_urls when posting in.

### ISSUE THREAD

**Issue by agpar** [DDMAL/misirlou#9]
Currently there is no check to see that we do not already have a manifest indexed and stored in the DB. Clearly there should be one. The issue, as Will pointed out in #2 is how the event of a duplicate should be handled.

A redirect to the manifests page is not out of the question - or maybe we should simply handle this by deleting the old document and re-indexing in solr. I think this might be the most graceful way to handle it. We want to occasionally check if remote manifests have been updated, so using the opportunity of a duplicate in a POST to do so is, I think, reasonable.

**Comment by ahankinson** [comment]
I like the second option -- delete and re-index.

Maybe it's over-engineering, but I was thinking we could have a hash (MD5 or SHA1) of the manifest stored in Solr. We could also hash the URL. This would give us an easy way of seeing if we have the same URL but a different manifest, or the same manifest at different URLs.

Thoughts?

**Comment by agpar** [comment]
Wouldn't that alert us that we have a different manifest at the same url any time the remote manifest is updated? Do we handle that by deleting the old document, or creating a new one? It wouldn't tell us if one line had changed, or if it was an entirely new manifest - right? - just that something had changed.

If all this provides is the knowledge needed to _not_ have to re-index when the remote manifest is unchanged, then I think it might be overdoing things.

**Comment by ahankinson** [comment]
I can imagine a couple scenarios:

1) The URL changes, but not the manifest. A IIIF server moves from a 'beta' site to a release site, for example. Or someone is hosting the same manifest on two different servers.

2) The Manifest is updated, but the URL stays the same. Easy to imagine the scenario there.

For 2), it's pretty obvious that we want to support it. For 1) however, I think we should guard against having the same manifest appear twice, since that would artificially boost the results in that case.

I don't think we should get into `diff`ing to see what changed, but I think we should be able to say if we have two manifests that are the same at different URLs. So I'm happy to just delete and re-index the whole thing.

There may be a Solr-internal way of doing this. I just found: https://cwiki.apache.org/confluence/display/solr/De-Duplication. Have a look and see if it applies in this case.

**Comment by agpar** [comment]
I wasn't considering case 1. That's a good point.

**Comment by wabain** [comment]
Are there circumstances here where our URL for the manifest would change? That seems like it could be a problem.

There's also a question in my mind of whether we would _always_ want to reindex on POST. If a user submits a URL and we just indexed that URL, do we always want to do it again?

**Comment by agpar** [comment]
1) The _exact_ same manifest should never appear at a different URL, as its `@id` field must point to it's URL. Hashing full manifests will only be useful if we do fuzzy hashing, which worries me a tiny bit since there is so many repeated words in manifests that entirely different manifests of a similar length might have scarily high similarity ratings.

2) Exact URL matches are already being handled by a `delete all documents with exact same remote_url` call before indexing.

The de-duping is a cool feature, and I've played with it a little on a local branch, but I don't know if it will be applicable.

**Comment by agpar** [comment]
To Will's comment: We're already doing a check to see if a particular URL is already in our database (this should be consistent based on what I just wrote in #11), so we could also check the last time the manifest was indexed and only index it if hasn't been successfully indexed in the last 24h (or more).

**Comment by agpar** [comment]
Still not solved: a manifest being moved from one location to another, and being entirely the same except for it's `@id` field. We could do a strict hash across indexed fields - so if `label` and `type` and `description` and `metadata` and anything else besides `@id` are all the same then we consider it a duplicate.

But that's still a tough case. Do you delete the old one and replace it? What if both URLs are still valid?

**Comment by ahankinson** [comment]
Can't we just get the URL from the manifest `@id` and the strict hash from the manifest itself? Then it's like two-factor authentication -- they should both pass.

If a manifest hashes the same but its URL is different you _must_ delete the manifest with the old URL and add a new record with the new URL and the manifest.

**Comment by agpar** [comment]
Here's the flow I'm looking at.
1. Get `manifest` from `remote_url`
2. Get `manifest2` from `manifest[@id]`
3. Hash the two and compare to assure they are the same.
4. Query solr for `manifest[@id]`. If it exists and was updated <24 hours ago, return.
5. Index in solr using `manifest[@id]` as URL
   1. Solr dedupes and replaces on exact URL matches 
   2.  Solr produces a hash `sig` based on all indexed fields (title, label, date, etc) 
6. Query solr to see if more than one doc with signature `sig` exists.
7. If 6, delete older doc and corresponding entry in DB

I'd rather not do automatic replacing on 5(ii) because then we'd have no way to know if solr found a dupe and replaced it - leading to conditions where we have manifests in the DB which are not indexed in solr.

**Comment by wabain** [comment]
This seems to be mostly implemented. Is there more to do on it?

**Comment by agpar** [comment]
Yeah - it's not quite implemented. I'm fooling around with solr right now to get it going.

**Comment by wabain** [comment]
Cool. I just wanted to check that this issue wasn't stale.

**Comment by agpar** [comment]
While implementing solr deduping, I frustratingly posted on the apache solr wiki saying their examples ~~sucked real bad~~ could be improved for users who wanted to implement the bare-bones features quickly/easily.

https://cwiki.apache.org/confluence/display/solr/De-Duplication?focusedCommentId=61327863#comment-61327863

World = better place.

**Comment by ahankinson** [comment]
:+1:
