### ISSUE TITLE
Small front page fix-ups

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#91]
1. Change "Recently uploaded" to "Selected items"
2. Move the "Searching x documents from y sources" to just below the search bar ("Pitch search" on the right, this statement on the left.)

**Comment by lexpar** [comment]
"make the header" ?

**Comment by ahankinson** [comment]
I have no idea what you mean. ;)

**Comment by lexpar** [comment]
What comment are you replying to? I'm even more confused.

**Comment by ahankinson** [comment]
Clearly there is some sort of miscommunication here.

**Comment by agpar** [comment]
What?

**Comment by agpar** [comment]
#WorkingHard

**Comment by agpar** [comment]
~~I changed the text to say "Search from X documents" since the source counting is sort of off base and a small number.~~
I wrote a better way to count libraries, so we can use that now.

**Comment by agpar** [comment]
![image](https://cloud.githubusercontent.com/assets/9021839/16391098/8f57ddd0-3c73-11e6-808d-3d298955e386.png)

**Comment by agpar** [comment]
Unless I've misunderstood something, this should be done.
