### ISSUE TITLE
Fix diva viewer sometimes not showing the correct initial page

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/misirlou#95]
I just implemented a feature where the initial page shown by Diva is now the page containing the first OMR result. However, I ran into an issue with Diva while coding it and had to use a workaround. Here is the issue in question:

Right after Diva has loaded, I try to use Diva's gotoPageNumber method. At this point I am sure that the diva instance has been created and the method in question returns me true, meaning that the page number is valid. However, _most of the time,_ the page did not change.
I had to used a setTimeout in order to add a delay between the instantiation of diva and the page change. This delay is currently set to 100ms and I have noticed a few times where the page still did not change.

This is obviously not an optimal solution and needs some investigation. I believe this is a non-trivial problem to solve and will take quite some time to figure out. For @ahankinson 's presentations, I could set the delay to be a bit longer just to make sure it works.

Note that this could also be a Diva issue.

**Comment by jeromepl** [comment]
Here is the code I am talking about: https://github.com/DDMAL/musiclibs/commit/1f0ed40b3db9ecf62ce57224e63f49f799ca7ea8#diff-8165737331ce05a19750bfe9efbff7efR64

**Comment by ahankinson** [comment]
You could listen for `ViewerDidLoad` and then call the method in question. That way you're guaranteed that the viewer is completely loaded with all the pages before firing the gotopage method.

**Comment by jeromepl** [comment]
I have tried it with `DocumentDidLoad` and it seems to work! Finishing this atm.
