### ISSUE TITLE
Auto-link URLs in manifests

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#97]
If a manifest has a URL in the metadata field, we should render it as a link in the description.

**Comment by agpar** [comment]
I'm not sure I understand the problem. Are you saying that any URL from a manifests metadata should be automatically converted to hyperlink on the detail page?

**Comment by ahankinson** [comment]
Yeah -- the gallica stuff, for example, has a bunch of links embedded in it.

**Comment by jeromepl** [comment]
Here is a nice regex for that: ^(https?:\/\/)([\da-z.-]+).([a-z.]{2,6})([\/\w .-]_)_\/?$
I am assuming here that we only want to create a link when the http/https is specified.

**Comment by ahankinson** [comment]
I don't know... [`archie://`](https://en.wikipedia.org/wiki/Archie_search_engine) links would be kinda cool too... 

(I'm kidding.)

**Comment by agpar** [comment]
#McGillPride
